### ISSUE TITLE
Kysely + Objection.js

### ISSUE THREAD

**Issue by calmonr** [koskimas/kysely#1]
Is there any intent of switching from Knex.js to Kysely in the future on Objection.js?

Nice work by the way.

**Comment by koskimas** [comment]
Thanks! Probably not, for the same reason I'm not contributing this to knex. It would mean a significant rewrite and API change.

**Comment by calmonr** [comment]
@koskimas You are totally right. Keep up the good work.

**Comment by mmahalwy** [comment]
to that point, @koskimas curious if youd build objectionjs or a new orm from the start?

**Comment by seeden** [comment]
I am curious as well :) maybe it will be part of this package directly :)

**Comment by kasvith** [comment]
Will there be a new ORM like Objection?

**Comment by seeden** [comment]
@kasvith you can try https://github.com/seeden/kysely-orm

**Comment by kasvith** [comment]
@seeden it seems really nice

**Comment by mifi** [comment]
[drizzle orm](https://github.com/drizzle-team/drizzle-orm) also feels like objection but it is fully type-safe

**Comment by kasvith** [comment]
tbh drizzle feels like prisma, where objection was much more like a wrapper around a query builder. we still use it in production

**Comment by mifi** [comment]
I also use Objection in production and it's great. But seeing that Objection has slowed down development and its lacking type safety, moving forward I'm looking for alternatives. What I love about objection is that it allows customisable querying of deep table relations into a JSON structure without too much magic (withGraphFetched). And I can still include raw sql or use knex alongside to run more complex raw queries. IMO drizzle also feels like a thin layer over sql similar to knex/kysely, but it has the added benefit of being able to easily specify and query relations into JSON objects, kind of like Objection. Prisma feels like a higher and heavier layer which abstracts away differences between SQL flavours, and it may generate an arbitrary number of sql queries based on your query. For me the biggest issues with drizzle are:
- it's quite new and unstable (0.x)
- it needs "lateral join" support which only the newest mysql/postgresql versions support and many hosted DB services like aws aurora and planescale do not support

**Comment by kasvith** [comment]
i wish objection had continuous development :( ngl apart from typesafety its the best ORM even today
