### ISSUE TITLE
TypeError: db.raw is not a function  when trying to make an aggregate

### ISSUE THREAD

**Issue by t-indie** [koskimas/kysely#103]
Hello,

my goal is to make a _json_agg_, I tried to follow the examples mentioned [here](https://github.com/koskimas/kysely/issues/31#issuecomment-988155044)  but I get TypeError: db.raw  as explained [here](https://github.com/koskimas/kysely/issues/31#issuecomment-1145724133) in details.

I am on  v 0.19.3 but also tried on v 0.18.1 with no luck

any help would be appreciated :)

**Comment by koskimas** [comment]
`db.raw` was replaced by the `sql` template tag [a while ago](https://github.com/koskimas/kysely/releases/tag/0.17.0).

Now you'd do something like this:

```ts
function json_agg<DB, TB extends keyof DB, O = {}>(qb: QueryBuilder<DB, TB, O>) {
  return sql<O[]>`coalesce((select jsonb_agg(x) from (${qb}) x), '[]'::jsonb)`
}
```

**Comment by t-indie** [comment]
That worked thanks a lot
