### ISSUE TITLE
MATCH AGAINST Syntax

### ISSUE THREAD

**Issue by rcoundon** [koskimas/kysely#104]
This is such a good library and amazing use of TypeScript inference.

The challenge I have is that I need to be able to issue a query that includes MATCH AGAINST for a field that is indexed as FULLTEXT but can't seem to figure out the safe, correct syntax.

I can do it like this:
```query.where(sql`MATCH(the_field_name) AGAINST (${someValue} IN NATURAL LANGUAGE MODE)`);```

However, I rather this was parameterised, something like this:
```query.where(sql`MATCH(the_field_name) AGAINST (? IN NATURAL LANGUAGE MODE)`, '=', someValue);```

The latter example builds a query that looks like:
```where MATCH(EL_Notes_Dispo) AGAINST (? IN NATURAL LANGUAGE MODE) = ?```

Whereas I'd like for the ? placeholder to be substituted. Is there some syntax that I can use in Kysely to achieve this?

(P.S. I'd love to join the Discord to ask this kind of question but the chat link on Github shows an invitation expired error)

**Comment by koskimas** [comment]
Your first example IS parametrized. Just take a look at the generated SQL. The `sql` template tag takes care of the parametrization. It doesn't actually interpolate the value into the SQL.

**Comment by rcoundon** [comment]
> The discord link is set to never expire. It's not expired. Discord only allows me to create one link with an infinite expiry time, so I can't create a new one without deleting the current one. I can't delete the current one as it has been shared in multiple places.
Strange - this is what I see when I click on it
<img width="969" alt="image" src="https://user-images.githubusercontent.com/9136570/173590991-6b0fa5e9-c34c-45b6-afa6-daf514899b9b.png">

**Comment by koskimas** [comment]
This is what I get when I click on it (in incognito mode);

<img width="1433" alt="Screenshot 2022-06-14 at 17 06 25" src="https://user-images.githubusercontent.com/846508/173597275-eeaee6a8-a9f3-432a-a9cd-46d5e3d5fd99.png">
