### ISSUE TITLE
"create schema if not exists" is not working if plugin is used.

### ISSUE THREAD

**Issue by borissuska** [koskimas/kysely#108]
I've created plugin to inject schema into queries to avoid using `withSchema` method with every query. Later I found out it's same as build-in `WithSchemaPlugin`. I've been using migrations too and trying force `Migrator` to use schema. In this combination migration fails because of "SCHEMA ALREADY EXISTS" error.

I've been debugging for a while and found out root cause of the problem, then I fixed it with another bug in the PR #107

**Comment by koskimas** [comment]
Nicely found and fixed! 👍 I'll review the PR once I get to a computer (in a couple of days, I'm in a festival and quite intoxicated).

**Comment by koskimas** [comment]
PR merged. Thank you!

**Comment by koskimas** [comment]
0.19.7 now has your fix.
