### ISSUE TITLE
Extract select builder while preserving types

### ISSUE THREAD

**Issue by Loskir** [koskimas/kysely#109]
If I write this query:
```ts
const data = await db
  .selectFrom('Product')
  .select(['productId', 'name'])
  .execute()
```

I get type completion on data: `productId` and `name`.

But if I want to extract select query to reuse it later like this:

```ts
const productSelector: ReadonlyArray<SelectExpression<Database, 'Product'>> = [
  'productId',
  'name',
]
const data = await db
  .selectFrom('Product')
  .select(productSelector)
  .execute()
```

I get no completion, all fields are `any`.

How do I get this to work?

**Comment by koskimas** [comment]
This is one way:

```ts
const productSelector = [
  'productId',
  'name',
] as const // <-- This part is the key!

const data = await db
  .selectFrom('Product')
  .select(productSelector)
  .execute()
```

If you write this

```ts
const productSelector = ['productId', 'name']
```

The type becomes `string[]`. With `as const` the type is correctly `('productId' | 'name')[]`

**Comment by Loskir** [comment]
Thanks! What if I have a query builder included?

```ts
      (qb) =>
        qb
          .selectFrom('ProductPrice')
          .whereRef('Product.productId', '=', 'ProductPrice.productId')
          .select('ProductPrice.basePrice')
          .orderBy('ProductPrice.time', 'desc')
          .limit(1)
          .as('basePrice'),
```

**Comment by koskimas** [comment]
that should work just fine:

```ts
const productSelector = [
  'productId',
  'name',
  (qb) =>
    qb
      .selectFrom('ProductPrice')
      .whereRef('Product.productId', '=', 'ProductPrice.productId')
      .select('ProductPrice.basePrice')
      .orderBy('ProductPrice.time', 'desc')
      .limit(1)
      .as('basePrice'),
] as const 
```

**Comment by koskimas** [comment]
This works:

```ts
const productSelector = [
  'productId',
  'name',
  // You need to explicitly type the function argument to be able to reference the `Product` table.
  (eb: ExpressionBuilder<Database, 'Product'>) =>
    eb
      .selectFrom('ProductPrice')
      .whereRef('Product.productId', '=', 'ProductPrice.productId')
      .select('ProductPrice.basePrice')
      .orderBy('ProductPrice.time', 'desc')
      .limit(1)
      .as('basePrice'),
] as const 
```

**Comment by elitan** [comment]
What if I have something like this?


```js
    .select([
      "jobs.id",
      "jobs.title",
      "jobs.slug",
      "jobs.logoUrl",
      "occupationGroups.label as occupationGroupLabel",
      "municipalities.label as municipalityLabel",
      "municipalities.slug as municipalitySlug",
      "employers.name as employerName",
      "employers.organizationNumber as employerOrganizationNumber",
    ])
```

**Comment by igalklebanov** [comment]
> What if I have something like this?
> 
> ```js
>     .select([
>       "jobs.id",
>       "jobs.title",
>       "jobs.slug",
>       "jobs.logoUrl",
>       "occupationGroups.label as occupationGroupLabel",
>       "municipalities.label as municipalityLabel",
>       "municipalities.slug as municipalitySlug",
>       "employers.name as employerName",
>       "employers.organizationNumber as employerOrganizationNumber",
>     ])
> ```

In many cases, Kysely's builders have 2 main generics, `DB, TB extends keyof DB`, which are basically the DB interface you passed originally to the constructor (could include additional aliased tables) and a union type of table names in current query's context.

So the `TB` in your case should be `'jobs' | 'occupationGroups' | 'municipalities' | 'employers'`.
