### ISSUE TITLE
Alarming error output sql

### ISSUE THREAD

**Issue by boehs** [koskimas/kysely#110]
Apologies, I am probably doing something horribly wrong. Inserts are failing with

```
 code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1",
``` 

Confused, I pasted the code into an SQL editor, and found that syntax highlighting was also broken. It breaks

```
'<p>Omie,</p><p>We aren\\'t in contact
                        ^^
                        here
```

And the problem becomes obvious! Single quotes are being escaped like `\\'`, when really they ought to be like `''`.

I'm unclear where this escaping code is even coming from. I did a search for escape and found nothing. Interestingly, `Connection.escape(value: any): string` is also escaping in a faulty way:

```
'<p>Omie,</p><p>We aren\'t in contact
```

So it's pretty unclear to me if this issue is coming from kysely or mysql2. I was hoping you could provide some insight.

Some other things

1. Regardless of the source of the problem, it's very concerning. Will a deliberate, more sophisticated attack be handled?
2. I can't escape manually, I tried and it just results in exponential `\\\\\\\\\`

**Comment by koskimas** [comment]
You should never ever ever ever ever concatenate user input to SQL strings! Instead you should pass all user input as parameters. Then, there's no need to escape anything, as the value is never added to the SQL string. Could you share the code that's causing that and I can point out how it should be written?

**Comment by boehs** [comment]
The code is simple

```
    await db
        .insertInto('ltc')
        .values([message: "<p>Omie,</p><p>We aren't in contact"], [message: "<p>Very cute. Nice try</p>"])
        .onDuplicateKeyUpdate({})
        .execute()
```

**Comment by koskimas** [comment]
There's absolutely no way that's causing the bug you reported, unless you are doing something crazy with plugins or using a third-party dialect.

**Comment by koskimas** [comment]
Here's one of the tens of tests I have for inserts and the SQL that's produced

```ts
      const query = ctx.db.insertInto('person').values({
        first_name: 'Foo',
        last_name: 'Barson',
        gender: 'other',
      })

      testSql(query, dialect, {
        postgres: {
          sql: 'insert into "person" ("first_name", "last_name", "gender") values ($1, $2, $3)',
          parameters: ['Foo', 'Barson', 'other'],
        },
        mysql: {
          sql: 'insert into `person` (`first_name`, `last_name`, `gender`) values (?, ?, ?)',
          parameters: ['Foo', 'Barson', 'other'],
        },
        sqlite: {
          sql: 'insert into "person" ("first_name", "last_name", "gender") values (?, ?, ?)',
          parameters: ['Foo', 'Barson', 'other'],
        },
      })
```
     
As you can see, the values are not concatenated to ths SQL.

**Comment by koskimas** [comment]
Actually it could happen if you are doing that in a migration? Is that migration code?

**Comment by koskimas** [comment]
Don't know what to tell you. I can't reproduce that.

**Comment by boehs** [comment]
Sure, I want to get to the bottom of this. One moment

**Comment by koskimas** [comment]
Actually that empty `onDuplicateKeyUpdate` is causing the query to fail but it has nothing to do with the input.

**Comment by boehs** [comment]
Oh interesting. Is it possible that when the query fails, it just dumps an odd output?

**Comment by boehs** [comment]
<details>
  <summary>The code</summary>

```ts

#!/usr/bin/env ts-node

import { Generated, Kysely, MysqlDialect } from "kysely"
import { createPool } from 'mysql2'

const letters = [
    {
        "Id": 13,
        "letterMessage": "<p>Omie,</p><p>We aren't in contact - that's. Recently, I haven't. I. If, all.</p><p>One hope, right? </p>",
        "letterPostDate": "/Date(1650851725000)/",
    },
    {
        "Id": 12,
        "letterMessage": "<p>Nothing special here. A few periods.",
        "letterPostDate": "/Date(1234567890000)/",
    }
]

interface LtcBase {
    letterMessage: string;
}

interface LtcTable extends LtcBase {
    id: Generated<number>
    letterPostDate: Date;
}

interface Database {
    test: LtcTable
}

let pool = createPool({
    database: "your",
    host: "localhost",
    user: "creds",
    password: "here"
})

const db = new Kysely<Database>({
    dialect: new MysqlDialect({
        pool: pool
    })
})

await db.schema
    .createTable('test')
    .addColumn('id', 'integer', (col) => col.autoIncrement().primaryKey())
    .addColumn('letterPostDate', 'datetime')
    .addColumn('letterMessage', 'text')
    .execute()


// @ts-ignore
const patchedJson: LtcTable[] = letters.map(letter => {
    delete Object.assign(letter, { ["id"]: letter["Id"] })["Id"]
    // @ts-ignore
    letter.letterPostDate = new Date(Number(letter.letterPostDate.split('/Date(')[1].split(')/')[0]))
    return letter
})

await db
    .insertInto('test')
    .values(patchedJson)
    .onDuplicateKeyUpdate({})
    .execute()

console.log('done')
```
</details>

You will need to add your credentials but otherwise should work fine.

Some observations

1. Without the `.onDuplicateKeyUpdate({})` the query does indeed work fine 🎉 🎉 
2. The error is *very concerning* with the `\\'`

```
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1",
  sql: "insert into `test` (`letterMessage`, `letterPostDate`, `id`) values ('<p>Omie,</p><p>We aren\\'t in contact - that\\'s. Recently, I haven\\'t. I. If, all.</p><p>One hope, right? </p>', '2022-04-24 21:55:25.000', 13), ('<p>Nothing special here. A few periods.', '2009-02-13 18:31:30.000', 12) on duplicate key update "
}
```

3. Somehow this incorrect query worked 80 times before erroring (the for loop in the actual code posted above successfully iterated 80 times)

**Comment by koskimas** [comment]
I think mariadb is just printing the whole thing as SQL for some odd reason, but the error is from the invalid SQL caused by the wrong use of `onDuplicateKeyUpdate`.

Feel free to add console.logs to the kysely code to see what kysely sends to the `mysql2` driver. Kysely is definitely not doing something that stupid. And neither is mysql2.

The error `sqlMessage` has nothing to do with the `'` characters in the values.

**Comment by koskimas** [comment]
[Here's](https://github.com/koskimas/kysely/blob/961d112b9a5f3103c848163cb420f7acea757434/src/dialect/mysql/mysql-driver.ts#L151) the line where the query is sent to `mysql2`. You can edit that line in your `node_modules` to see what's happening.

**Comment by boehs** [comment]
Thank you! Sorry for that whole roller coaster. Is there some way I could buy you a coffee?

**Comment by koskimas** [comment]
There's no way or need to do that. Thanks for the offer though 😊
