### ISSUE TITLE
[Improvement] Check missing properties when type is copied

### ISSUE THREAD

**Issue by borissuska** [koskimas/kysely#111]
Hello, it's me again. I was curious how issue #108 should happen. Is there a way how to use typescript to check if all properties are used?

I was looking at `operation-node-transformer.ts` source code mainly. There is used class like this:

```typescript
export interface CreateSchemaNode extends OperationNode {
  readonly kind: 'CreateSchemaNode'
  readonly schema: IdentifierNode
  readonly ifNotExists?: boolean
}
```

and OperationNodeTransformer has copy method like this:

```typescript
protected transformCreateSchema(node: CreateSchemaNode): CreateSchemaNode {
    return {
      kind: 'CreateSchemaNode',
      schema: this.transformNode(node.schema),
      ifNotExists: node.ifNotExists,
    }
  }
```

if I remove `ifNotExists: node.ifNotExists,` line no typescript error occurs because `ifNotExists` property is optional. I was looking for some utility type like build in Required<T>. Sadly Required<T> is not compatible with original T type, in this case it requires `node.ifNotExists` not to be possibly undefined. Long story short, after all I found out this utility type:

```typescript
type AllProps<T> =  T & { [P in keyof T]-?: unknown; };
```

Now when I use the AllProps type like this 

```typescript
protected transformCreateSchema(node: CreateSchemaNode): AllProps<CreateSchemaNode> {
    return {
      kind: 'CreateSchemaNode',
      schema: this.transformNode(node.schema),
      // ifNotExists: node.ifNotExists,
    }
  }
```

Typescript shows error `Property 'ifNotExists' is missing in type '{ kind: "CreateSchemaNode"; schema: IdentifierNode; }' but required in type '{ readonly kind: unknown; readonly schema: unknown; readonly ifNotExists: unknown; }'` now. It's not very accurate, because type of all properties is unknown. In case of `ifNotExists` is initialised with string, Typescript shows `Type 'string' is not assignable to type 'boolean | undefined'.` error. Which is good enough because Typescript shows missing property and wrong property type errors. The only problem is, it changes OperationNodeTransformer interface, transform methods return type is AllProps<...Node> instead of ...Node, even types are compatible. 

I can add it to the library if you agree.

**Comment by koskimas** [comment]
Great idea! Feel free to implement and I'll merge. Thanks for looking into this 👍 

By the way, I added a `TEST_TRANSFORMER=1 npm test` run to CI. But that only catches the forgotten stuff if there's a test for the feature.

**Comment by koskimas** [comment]
PR merged. Thank you 👍
