### ISSUE TITLE
Feature request: special generic type to mark a db field as not null but with a default

### ISSUE THREAD

**Issue by KristjanTammekivi** [koskimas/kysely#1282]
Hi, 

I would like there to be a type that marks a field as a defaulted non-nullable field. I'll explain it through examples.
Current state

```typescript
interface DB {
  test: {
    id: number | null;
    name: string;
  };
}
const kysely = createKysely<DB>(testConfig);
const result = await kysely.insertInto('test').values({ name: 'test'}).returningAll().executeTakeFirst();
// Type of result is { id: number | null, name: string } even though id can never actually be null
```

One of the ways to resolve this is to have a special type that marks a field as optional for inserts but when selecting it will always resolve like this

```typescript 
interface DB {
  test: {
    id: DefaultNotNull<number>;
    name: string;
  };
}
```

**Comment by KristjanTammekivi** [comment]
Well yes, the reason I did that was so I wouldn't have to pass id into .values call, since it's defaulted. I could do this with an optional field but then the result id type is number | undefined, still wrong

**Comment by igalklebanov** [comment]
Have you read through [Getting Started](https://kysely.dev/docs/getting-started)?

**Comment by KristjanTammekivi** [comment]
Apparently I'm blind, thanks
