### ISSUE TITLE
Restrictions in union with with and withRecursive

### ISSUE THREAD

**Issue by lovis-ff** [koskimas/kysely#139]
The postgres `with recursive` query can refer to its own output. The syntax can look like this
```
WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t;
```

The kysely `union` method does only take a querybuilder as input which is not type aware of its surroundings.
Hence the following does not work:
```
db.withRecursive("t", qb =>
  qb
    .selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q"))
    .select("q.n")
    .unionAll(qb =>
      qb
        .selectFrom("t")
        .select(sql<number>`n+1`.as("n"))
        .where("t.n", "<", 100)
    )
);
```
because the `unionAll` does not accept a querybuilder function.
What does work, but has less type support, is using the raw sql builder in the unionAll
```
db.withRecursive("t", qb =>
  qb
    .selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q")
)
.select("q.n")
.unionAll(sql`select n+1 as n from t where t.n < 100`);
```

&nbsp;

The restriction in the `union` method makes it also harder to access the same with query in two union queries like this
```
with t as (
    select 1 as n
)
select * from t
union all select * from t
```
Here, the following does not work:
```
db.withRecursive("t", qb =>
    qb.selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q")).select("q.n")
  )
.selectFrom("t")
.select("n")
.unionAll(qb => qb.selectFrom("t").select("n"));
```
and even the following (which is not ideal) is not possible because of missing brackets in the resulting query
```
const qb1 = db
  .withRecursive("t", qb =>
    qb
      .selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q"))
      .select("q.n")
  )
  .selectFrom("t")
  .select("n");

const qb2 = db
  .withRecursive("t", qb =>
    qb
      .selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q"))
      .select("q.n")
  )
  .selectFrom("t")
  .select("n");

const qbUnion = qb1.unionAll(qb2);
```
which results in the following query
```
with recursive "t" as (select "q"."n" from (select 1 as n) as "q") select "n" from "t" union all with recursive "t" as (select "q"."n" from (select 1 as n) as "q") select "n" from "t"
```
throwing a syntax error:

> syntax error at or near "with"

&nbsp;

Are there any plans on allowing a callback function in the `union` and `unionAll` methods allowing us to have access to the typings?

**Comment by koskimas** [comment]
I'm not sure I understood your problem, but this works:

```ts
          const query = nodeTrx
            .withRecursive('ancestors(name, parent)', (db) =>
              db
                .selectFrom('node')
                .where('name', '=', 'node1')
                .select(['name', 'parent'])
                .unionAll(
                  db
                    .selectFrom('node')
                    .innerJoin('ancestors', 'node.name', 'ancestors.parent')
                    .select(['node.name', 'node.parent'])
                )
            )
            .selectFrom('ancestors')
            .select('name')
```

**Comment by koskimas** [comment]
So I think here's how to fix your query:

```ts
db.withRecursive("t(n)", qb =>
  qb
    .selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q"))
    .select("q.n")
    .unionAll(qb =>
      qb
        .selectFrom("t")
        .select(sql<number>`n+1`.as("n"))
        .where("t.n", "<", 100)
    )
);
```

**Comment by lovis-ff** [comment]
Ok, thanks a lot. That fixes the problem with the `withRecursive`. 
Any thoughts about the functionalities regarding the `union` method and the missing brackets in the query?
I would at least expect the resulting query to be
```
with "t" as (select "q"."n" from (select 1 as n) as "q") select "n" from "t" union all (with "t" as (select "q"."n" from (select 1 as n) as "q") select "n" from "t")
```
to make it working, so putting brackets around the union query.

**Comment by koskimas** [comment]
None of the postgres examples use parentheses around the unioned queries. Are you use nested with statements are even supported? Why not put all with statements on the top level?

**Comment by lovis-ff** [comment]
Yes that is my problem. 
So the nested with is working (but is nothing I would like to follow).
I am struggeling with having all with at the top, because I currently see no way of accessing the with query in the union query, but probably I am just missing something.

I would like to do this:
```
db.with("t", qb =>
    qb.selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q")).select("q.n")
  )
.selectFrom("t")
.select("n")
.unionAll(qb => qb.selectFrom("t").select("n"));
```
which does not work because the `unionAll` just accepts a `selectQueryBuilder`.
Hence I can only do this:
```
db.with("t", qb =>
    qb.selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q")).select("q.n")
  )
.selectFrom("t")
.select("n")
.unionAll(db.selectFrom("t").select("n"));
```
which gives me a typing error because the `db.selectFrom("t").select("n")` in the `unionAll` is not aware of the `"t"` withQuery.

What am I missing here?

**Comment by MoSheikh** [comment]
Hi, I actually have thge exact same use case as @lovis-ff in their example of 

```ts
db.with("t", qb =>
    qb.selectFrom(sql<{ n: number }>`(select 1 as n)`.as("q")).select("q.n")
  )
.selectFrom("t")
.select("n")
.unionAll(db.selectFrom("t").select("n"));
```

Are there any recommendations around this? Thank you!

**Comment by owenfarthing** [comment]
The [documentation](https://kysely-org.github.io/kysely-apidoc/interfaces/SelectQueryBuilder.html#union) for `union` and `unionAll` outlines how to pass a callback that gives access to an `ExpressionBuilder`. Using `.union(eb => eb.selectFrom('withClause')...)` with a `with` clause seems to provide access to that `with` and has type safety.

**Comment by lovis-ff** [comment]
Works for me now with using version 0.27.2.
