### ISSUE TITLE
How should I do for cross join ?

### ISSUE THREAD

**Issue by CrayonPastel** [koskimas/kysely#140]
Though I'd like to make a query using cross join, I cannot find such a function.
I found, instead, a similar function or 'innerJoinLateral' in the reference; however, TypeScript compiler returns a TS 2339 error when using it.

execute on ---
kysely 0.21.3
typescript 4.7.4
nestjs@cli 9.0.0
nodejs v17.9.0
postgres 13.2 on x86_64-pc-linux-gnu
vs code 1.70.1
ubuntu 20.04 LTS

**Comment by finaloop-igal** [comment]
Can you provide your query attempt, and perhaps the ts error description?

**Comment by koskimas** [comment]
You can simply select from two tables like this:


```ts
db.selectFrom(['t1', 't2'])
  .select(...)
  .where(...)
```

**Comment by koskimas** [comment]
Now that I read more about cross join, it seems to be the preferred syntax. We probably need to add a method for it, even though multiple `from` tables is equivalent.

**Comment by CrayonPastel** [comment]
It seems nice that plural tables can be simultaneously called in a single selectFrom. I didn't know such a usage.

Thanks a lot.

---
For your information.
On my environment, innerJoinLateral causes the following error.

ts(2339) : Property 'innerJoinLateral' does not exist on type 'SelectQueryBuilder<TableExpressionDatabase<any, "transaction", "transaction">, "transaction", {}>'.

```
import { Kysely } from "kysely";

export class Test extends Kysely<any> {
  public async test01(): Promise<any> {
    return await this.db
      .selectFrom('transaction')
      .innerJoinLateral( // this line result in ts(2339)
        (eb) => eb.selectFrom('master')
                  .select('product_name')
                  .whereRef('transaction.product_id', '=', 'master.product_id')
                  .as('m'),
        (join) => join.onTrue()
      )
      .selectAll()
      .execute();
  }
}
```

**Comment by koskimas** [comment]
I can't reproduce that. I think it might be caused by the fact that you use `any` as the database type and some combination of your typescript settings.

**Comment by CrayonPastel** [comment]
FYI

Now, I am aware that innerJoinLateral didn't work well due to my environment accidentally refering to an old version of kysely package instead of ver. 0.21.3. Excuse me.

**Comment by virtuallyunknown** [comment]
> Now that I read more about cross join, it seems to be the preferred syntax. We probably need to add a method for it, even though multiple `from` tables is equivalent.

I am not an SQL expert by any means, but for example if you have this query:

```sql
SELECT * FROM matches
CROSS JOIN USERS
LEFT JOIN predictions ON predictions.match_id = matches.id AND predictions.user_id = users.id
WHERE matches.id IN (1,2,3)
```

it's functionally not the same as:

```sql
SELECT * FROM matches, users
LEFT JOIN predictions ON predictions.match_id = matches.id AND predictions.user_id = users.id
WHERE matches.id IN (1,2,3)

-- Error: invalid reference to FROM-clause entry for table "matches"
```

Luckily, the there is a solution, which is to `JOIN on TRUE`.

[https://kyse.link/?p=s&i=Q6zLw2raDQR2hTCM24yC](https://kyse.link/?p=s&i=Q6zLw2raDQR2hTCM24yC)

```ts
await kysely
  .selectFrom('matches')
  .selectAll()
  .innerJoin('users', join => join.onTrue())
  .leftJoin('predictions', join => join
    .onRef('predictions.matchId', '=', 'matches.id')
    .onRef('predictions.userId', '=', 'users.id')
  )
  .execute()
```

```sql
SELECT
  *
FROM
  "matches"
  INNER JOIN "users" ON TRUE
  LEFT JOIN "predictions" ON "predictions"."matchId" = "matches"."id"
  AND "predictions"."userId" = "users"."id"
WHERE
  "matches"."id" IN ($1, $2, $3)
```

Althought I am not sure what I would do here if I needed an `OR` operator instead of and `AND` inside the `LEFT JOIN`. Probably would need a subquery.
