### ISSUE TITLE
Simplify result type

### ISSUE THREAD

**Issue by AzSiAz** [koskimas/kysely#141]
Hello,
Is it possible to make it so `execute`, `executeTakeFirst` and `executeTakeFirstOrThrow` return simplified (or extracted from complex type) array/object type instead of a complex type making kind of hard to read for complex query

I know I can "reduce" the type myself by using a custom and compatible type but I am wondering if that's something feasible and desirable for all  of the execute function in the library itself 🤔

**Comment by koskimas** [comment]
There's no way to do that automatically. You either get complex automatic magical types with lovely autocompletion, or you get simple readable types. Unfortunately both is simply impossible.

**Comment by AzSiAz** [comment]
Yeah, thought so too but was not sure how it's working, thanks for the quick answer 👍
