### ISSUE TITLE
Why is supportsReturning false in SqliteAdapter?

### ISSUE THREAD

**Issue by waynebloss** [koskimas/kysely#147]
Hello. Since SQLite and `better-sqlite3` both support the `RETURNING` clause [0, 1], I would have expected `SqliteAdapter.supportsReturning` to be `true` as well.

Is there some reason why it's `false`?

- [0] https://www.sqlite.org/lang_returning.html
- [1] https://github.com/WiseLibs/better-sqlite3/search?l=Markdown&q=returning&type=commits

**Comment by koskimas** [comment]
I don't know.
