### ISSUE TITLE
Consider enabling GitHub discussions

### ISSUE THREAD

**Issue by waynebloss** [koskimas/kysely#155]
Hello, thanks for creating a Discord for discussion. Unfortunately, I don't think Google indexes Discord and  the endless chat log may not be the best way to organize a Q&A.

Would you consider enabling the Discussions feature here on the GitHub repo as an alternative?

**Comment by koskimas** [comment]
We have issues and discord. I think a third place for discussions would just be confusing.

**Comment by koskimas** [comment]
@waynebloss I created [a poll](https://github.com/koskimas/kysely/issues/168) about this
