### ISSUE TITLE
Unhelpful typing error

### ISSUE THREAD

**Issue by Jazcash** [koskimas/kysely#161]
Am trying to insert values into a table, and there's a type error somewhere, because I imagine one of the values has a mismatching type, but the error doesn't say which property.

![image](https://user-images.githubusercontent.com/1434248/190424751-7311d2c4-3c3e-443d-b621-5cda805d3ca5.png)

I know there's no properties missing, because it would show here:

![image](https://user-images.githubusercontent.com/1434248/190425121-ed1456ba-866a-406d-926b-15a3d03646d9.png)

Any ideas?

**Comment by igalklebanov** [comment]
We have little to no control over compiler error text.

Paste (not screenshot) your code + database interface please.

**Comment by Jazcash** [comment]
Ok, that's a shame. I figured out my issue in the end after commenting out each property one and by one and realising one was missing `| undefined`
