### ISSUE TITLE
Custom type in generated types

### ISSUE THREAD

**Issue by daniel-gato** [koskimas/kysely#166]
Hi,

Is it possible to indicate a custom type the generated types from the migrations?

I have a status field that is a string in my migration but it is an ENUM in my business logic.

**Comment by koskimas** [comment]
Kysely doesn't support type generation at all. You are probably using [kysely-codegen](https://github.com/RobinBlomberg/kysely-codegen)?

**Comment by daniel-gato** [comment]
Ah, yes you are right. Sorry for that. We are using serverless stack and there is a bunch of stuff it uses.

mer are still trying to figure out what is what.
