### ISSUE TITLE
Get Primitive Type From Table Type?

### ISSUE THREAD

**Issue by bestickley** [koskimas/kysely#167]
Is there a utility type available to get a primitive type from a table type?

Let's say I have this table:
```ts
interface PersonTable {
  id: Generated<number>;
  first_name: string;
  gender: 'male' | 'female' | 'other';
  last_name: string | null;
  modified_at: ColumnType<Date, string | undefined, never>;
}
```

How can I get this type from it?
```ts
interface Person {
  id: number;
  first_name: string;
  gender: 'male' | 'female' | 'other';
  last_name: string | null;
  modified_at: Date;
}
```

Use Case: I'd like to derive the types I use on the front-end from my table types.

**Comment by bestickley** [comment]
Maybe exposing the type, `AllSelection` ? 
![image](https://user-images.githubusercontent.com/35735118/191348756-a1fc85c3-972c-4578-8bcc-0fd0b51e70ba.png)

**Comment by igalklebanov** [comment]
try `Selectable<Table>` and `SelectType<ColumnType>` helpers.

**Comment by bestickley** [comment]
@igalklebanov, thank you! With `Selectable` I can do the following:

```ts
type Person = Selectable<PersonTable>;
```
