### ISSUE TITLE
Updateable<T> allow undefined?

### ISSUE THREAD

**Issue by bestickley** [koskimas/kysely#170]
Why cannot Updateable<T> allow `undefined`?

I'm using zod for input validation. For an update, all properties besides an id should be optional. However, this seems to not allow me to use `.set` within Kysely because it does not allow undefined.

Use case:
```ts
import { Kysely, KyselyConfig, Updateable } from "kysely";
import { z } from "zod";

interface UserTable {
  id: number;
  firstName: string | null;
  lastName: string | null;
}
interface Database {
  user: UserTable;
}
const db = new Kysely<Database>({} as KyselyConfig);

const userSchema = z.object({
  id: z.number(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
});

const user = userSchema.parse({
  id: 1,
  firstName: "Ben",
});

// doesn't work
db.updateTable("user").set(user).where("id", "=", 1).execute();
// works
db.updateTable("user")
  .set(user as Updateable<UserTable>)
  .where("id", "=", 1)
  .execute();

```

Error:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/35735118/191946482-c0c0b356-1479-46af-841b-96aaaf01a85f.png">

**Comment by bestickley** [comment]
Found a work around updating my tsconfig to:
```json
{
  "extends": "@tsconfig/node16-strictest-esm/tsconfig.json",
  "compilerOptions": {
    "exactOptionalPropertyTypes": false // UPDATE HERE
  },
}
```
but I'd prefer to keep all strict TS checks on if possible. I'd still like this library to consider allowing `Updateable` to accept `undefined`

**Comment by igalklebanov** [comment]
Try adjusting `UserTable` as follows:

```ts
interface UserTable {
  id: GeneratedAlways<number>;
  firstName: ColumnType<string | null, string | undefined, string | undefined>;
  lastName: ColumnType<string | null, string | undefined, string | undefined>;
}
```

**Comment by bestickley** [comment]
@igalklebanov, so in the docs when it says:

// If the column is nullable in the database, make its type nullable.
// Don't use optional properties. Optionality is always determined
// automatically by Kysely.

it's saying don't use `{ key?: string }` but you **can** use `{ key: string | undefined }`?

**Comment by igalklebanov** [comment]
`Kysely` is not developed with such strict tsconfig, which is another topic of discussion.

I've found a fix for this issue, and it doesn't seem to break other things, so I'm pushing it.

**Comment by bestickley** [comment]
awesome. thanks, @igalklebanov! This seems like a very common use case.
I hope your PR gets merged, but if it cannot maybe Kysely could export a helper type like `type NullableColumn<T> = ColumnType<T | null, T | undefined, T | undefined>`.

**Comment by koskimas** [comment]
`undefined` and missing property are both allowed unless `exactOptionalPropertyTypes` is true, which treats these two as different cases. This is a common case, but people using this strict settings is not.

Let's fix this unless we need hacks to support this.
