### ISSUE TITLE
Serialize timestamptz to Date?

### ISSUE THREAD

**Issue by bestickley** [koskimas/kysely#172]
How can I serialize PostgreSQL data type `timestamptz` to Date? Is there a plugin? The docs have an example Table with the property: `modified_at: ColumnType<Date, string | undefined, never>` which implies this is possible (notice `Date`) but I'm not sure how. Thanks!

**Comment by igalklebanov** [comment]
This might help..

https://github.com/brianc/node-pg-types

**Comment by bestickley** [comment]
Ah got it. So it would be configured within `PostgresDialect`. Thanks!
