### ISSUE TITLE
Issue while extracting init logic to separate module

### ISSUE THREAD

**Issue by jmezzeragp** [koskimas/kysely#175]
Hi. I've been checking this tool for a few days and find it amazing, thanks!!

I'm developing a serverless application that will deploy a number of different lambdas, many of which need to access kyselys functionalities. For that, I want to extract the init logic `new Kysely<Database>{...}` to a reusable method which can be called from the different functions that require it.

My current codebase is as follows
``` typescript
const createDBConnection = () => new Kysely<SilverTables>({
    dialect: new MysqlDialect({
        // Empty pool configuration. Pool is mandatory to instantiate a Kysely object.
        // We won't be relying on Kysely to execute the query, only to build it.
        pool: createPool({}),
    })
})

const db = createDBConnection();

//entry point
const handler: Handler<APIGatewayEvent, ReturnType> = async (event) => {
    const queryBuilder = createQueryBuilder('1');
    const queryResult = await executeQuery(queryBuilder);

    return queryResult;
}

const createQueryBuilder = (id: string) => db.selectFrom('table).where('id', '=', id).select(['column']);

const executeQuery = <DB, TB extends keyof DB, O>(queryBuilder: SelectQueryBuilder<DB, TB, O>): Promise<O[]> => {
    const compiledQuery = queryBuilder.compile();
    let queryString = compiledQuery.sql;
    const params = compiledQuery.parameters;

    for (const param of params)
        queryString = queryString.replace('?', String(param));

    return dataAccessAPI(queryString);
}

```

If if move the `createDBConnection` method to a separate module, I start getting the following error: `Property '#private' in type 'SelectQueryBuilder' refers to a different member that cannot be accessed from within type 'SelectQueryBuilder'.`. Any ideas? 

Thanks in advance

**Comment by igalklebanov** [comment]
Are you using any framework such as `sst` to build your ser erless app?

**Comment by jmezzeragp** [comment]
SAM, but at this stage, the issue (IMHO) is not related to the app architecture

**Comment by igalklebanov** [comment]
If stuff starts breaking when you're moving code around, I'd suspect the build tools and frameworks as well..

We're using `kysely` in production, exposing a similar "gimme db instance" function from a local package to other modules in our monorepo, and we haven't had such issues.

What `kysely` version are you using? Are you using other `kysely` related packages?

Could you provide a repository that reproduces this issue?

**Comment by koskimas** [comment]
This is a little bit off topic, but regarding the `createDBConnection` function: you don't need to create a dummy mysql pool. You can do this instead:

```ts
const createDBConnection = () => new Kysely<SilverTables>({
    dialect: new MysqlDialect({
        createAdapter: () => new MysqlAdapter()
        createDriver: () => new DummyDriver(),
        createIntrospector: (db: Kysely<unknown>) => new MysqlIntrospector(db),
        createQueryCompiler: () => new MysqlQueryCompiler(),
    })
})
```

This way your module doesn't depend on the `mysql2` dialect at all. All of those classes can be imported from `kysely`.

**Comment by koskimas** [comment]
@jmezzeragp Feel free to continue the discussion here even though I closed it.
