### ISSUE TITLE
Introspector does not differentiate between enums of different schemas

### ISSUE THREAD

**Issue by RobinBlomberg** [koskimas/kysely#178]
### Problem

If a Postgres column uses the type `test.status`, the introspector simply infers it as `status`, so enum name collisions are possible.

```ts
import { Kysely, sql } from 'kysely';

const up = async (db: Kysely<any>) => {
  await db.transaction().execute(async (trx) => {
    await trx.schema
      .createSchema('test')
      .ifNotExists()
      .execute();

    await trx.schema
      .withSchema('test')
      .createType('status')
      .asEnum(['FOO', 'BAR'])
      .execute();

    await trx.schema
      .createType('status')
      .asEnum(['CONFIRMED', 'UNCONFIRMED'])
      .execute();

    await trx.schema
      .createTable('users')
      .addColumn('user_status', sql`status`)
      .addColumn('user_status_2', sql`test.status`)
      .execute();
  });
};

```

```ts
// Introspection result:
[{
  {
    dataType: 'status',
    enumValues: null,
    hasDefaultValue: false,
    isAutoIncrementing: false,
    isNullable: true,
    name: 'user_status',
  },
  {
    dataType: 'status',
    enumValues: null,
    hasDefaultValue: false,
    isAutoIncrementing: false,
    isNullable: true,
    name: 'user_status_2',
  },
}]
```

### Possible solutions

- Include the schema in the data type (feels like a scary/breaking change): `dataType: 'test.status'`
- Add a schema property: `dataTypeSchema: 'public'`

**Comment by koskimas** [comment]
I'd say `dataTypeSchema` is better

**Comment by igalklebanov** [comment]
@RobinBlomberg are you taking this?

**Comment by RobinBlomberg** [comment]
I have a `kysely-codegen` backlog I have to plow through when I get less busy, so I can't maybe any promises. But if this issue remains open, I may jump on it later.

**Comment by koskimas** [comment]
@RobinBlomberg This will be implemented in the next release. All postgres columns have the new `dataTypeSchema` field set. The default value is `pg_catalog` which is the schema of all built-in postgres types.

**Comment by RobinBlomberg** [comment]
Fantastic! 🙌
