### ISSUE TITLE
RFC: Decorators support

### ISSUE THREAD

**Issue by 0xDing** [koskimas/kysely#18]
Big Thanks to @koskimas  for writing this amazing library. 

Did kysely consider supporting class-based type definition?  Different from interface, class support decorators. And it's which helps us to implement more powerful and flexibility features. 

For example:

Typescript property decorators could set metadata for the class. This means we can use the `KyselyPlugin` to create plugins like auto-update updatedAt, encrypted fields, hashed password, etc.

And this can also be used to solve the problem in #5 

This can make kysely more powerful than sql builder and more flexible than ORM

**Comment by koskimas** [comment]
I specifically didn't use classes. They bring way more problems than they solve. Fore example if you do something like `Pick<SomeClass, 'someProperty'>` for a class, the result is no longer the class in any way, even though the wanted result us "the class without other properties than `someProperty`". I'm also the author of objection.js and one of the design choices I regret the most is using classes for defining the models.
