### ISSUE TITLE
Possible to add the query information to PluginTransformResultArgs?

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#189]
I'm trying to write a plugin to notify me after an INSERT/UPDATE/DELETE query is executed. Right now I'm just using a custom dialect but I think a plugin would be a better place for this.

Would it be possible to add a node variable to PluginTransformResultArgs like on PluginTransformQueryArgs, that just passes the original query node along? Or is there a better way to do this that I'm missing? I do need to call a callback after the query is executed, not before.

Edit: I just realized I could store the QueryId and link them together that way, I assume it's done that way for a reason.

**Comment by igalklebanov** [comment]
> Edit: I just realized I could store the QueryId and link them together that way, I assume it's done that way for a reason.

You should use a `WeakMap<QueryId, RootOperationKind>` for that.

**Comment by koskimas** [comment]
The `queryId` is there exactly for this reason. It allows you to share any data between the plugin methods, not just the node tree. It's all explained in the [docs](https://koskimas.github.io/kysely/interfaces/KyselyPlugin.html#transformQuery).

Once again, simply `cmd-click` the `KyselyPlugin` class to see the docs.

**Comment by midwesterntechnology** [comment]
Yep sorry about that, somehow I missed it on the docs, only noticed in when it popped up in Visual Studio. Thanks!

Threw together a basic plugin to handle this so i could just pass in a callback

```
import { RootOperationNode, QueryResult, UnknownRow, KyselyPlugin, PluginTransformQueryArgs, PluginTransformResultArgs, OperationNodeKind } from "kysely"
import { QueryId } from "kysely/dist/cjs/util/query-id"

export type HookPluginOptions = {
    before?: (node: RootOperationNode) => void
    after?: (node: RootOperationNode, result: QueryResult<UnknownRow>) => void
}

export default class HookPlugin implements KyselyPlugin {

    private data = new WeakMap<QueryId, RootOperationNode>()

    constructor(private readonly options: HookPluginOptions) {
    }

    transformQuery(args: PluginTransformQueryArgs) {
        this.data.set(args.queryId, args.node)
        this.options.before?.(args.node)
        return args.node
    }
    async transformResult(args: PluginTransformResultArgs) {
        const data = this.data.get(args.queryId)
        if (data !== undefined) {
            this.options.after?.(data, args.result)
        }
        return args.result
    }

}
export type MultiHookPluginOptions = {
    before?: { [k in OperationNodeKind]?: (node: RootOperationNode) => void }
    after?: { [k in OperationNodeKind]?: (node: RootOperationNode, result: QueryResult<UnknownRow>) => void }
}

export class MultiHookPlugin implements KyselyPlugin {

    private data = new WeakMap<QueryId, RootOperationNode>()

    constructor(private readonly options: MultiHookPluginOptions) {
    }

    transformQuery(args: PluginTransformQueryArgs) {
        this.data.set(args.queryId, args.node)
        this.options.before?.[args.node.kind]?.(args.node)
        return args.node
    }
    async transformResult(args: PluginTransformResultArgs) {
        const data = this.data.get(args.queryId)
        if (data !== undefined) {
            this.options.after?.[data.kind]?.(data, args.result)
        }
        return args.result
    }

}
```
