### ISSUE TITLE
Simplify Query Result types

### ISSUE THREAD

**Issue by riyaadh-abrahams** [koskimas/kysely#190]
Hi

Is it possible to have Kysely `execute()` functions to return a nicer-looking type that shows all properties on hover? Currently a query like this: 
```ts
    const user = await k .selectFrom("User").selectAll().where("id", "=", 1).executeTakeFirstOrThrow();
```
would result in a hover preview like this:
```
const user: AllSelection<From<DB, "User">, "User">
```

I was looking at issue #141 where it was mentioned that it was not possible. However, I did find a potential solution on this [StackOverflow post](https://stackoverflow.com/questions/57683303/how-can-i-see-the-full-expanded-contract-of-a-typescript-type). 

Essentially using this helper I was able to get a nice-looking type:
```ts
export type ExpandRecursively<T> = T extends object
  ? T extends infer O
    ? { [K in keyof O]: ExpandRecursively<O[K]> }
    : never
  : T;
```
First I was able to run the query result through the helper:
```ts
const user = await k .selectFrom("User").selectAll().where("id", "=", 1).executeTakeFirstOrThrow();
type UserCool = ExpandRecursively<typeof user>;
```
which resulted in a hover preview: 
```
type UserCool = {
    id: number;
    name: string;
    email: string;
    picture: string | null;
}
```

I am not sure what the downsides of this are. but maybe there is some way to integrate something like this into kysely?

**Comment by igalklebanov** [comment]
I like the idea of this, and have played around with such helpers before..

Not sure how safe it is ([`type-fest`](https://github.com/sindresorhus/type-fest/blob/main/source/conditional-simplify.d.ts) has this as *experimental*), how worse the typescript performance gets..

Needs testing on very complex kysely select queries, in large codebases..

**Comment by riyaadh-abrahams** [comment]
Oh yes, definitely opt-in. I guess it could even work similarly to zod's [Type Inference](https://github.com/colinhacks/zod#type-inference).

**Comment by koskimas** [comment]
Yeah, not possible.

**Comment by igalklebanov** [comment]
> Oh yes, definitely opt-in. I guess it could even work similarly to zod's [Type Inference](https://github.com/colinhacks/zod#type-inference).

`zod` doesn't simplify it's infered types. You get a whole lot of `ZodEffects` wrappers and other shenanigans. You're forced to use their `infer/input/output` helpers to get simplified structures in hints.
