### ISSUE TITLE
Kysely Converts Int8Array to object (not array) after query

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#191]
I'm having an issue pulling an Int8Array out of the database using Kysely.

At some point _after_ my custom dialect's executeQuery method, an Int8Array coming from the DB (this is how wa-sqlite does blobs) is being converted to an object (the keys being the indexes of the former array). I've checked what I'm returning from executeQuery and it's still an Int8Array at that point. Just for kicks, I modified the driver to change the field to some other byte array types, Uint8Array, Uint32Array, and it has the same issue there. If I convert it to a regular Array (Array.from(int8arraydata)) on the other hand, it works fine.

So it seems that something in Kysely, after the driver returns the data, but before the query results are returned, is turning Int8Array and similar types into to an object. Is there a workaround for this besides just converting the object back and forth, or modifying the DB calls/driver, or is this something that can be changed? Checked the docs but could not find much of anything on how blobs / byte arrays are handled.

```
const localFile = await this.db.kysely.selectFrom("localFiles").where("id", "=", upload.id).select("myint8arrayfield").executeTakeFirst()
//this is an object ^
```

```
      async executeQuery<O>(compiledQuery: CompiledQuery) {
        const results = await dialect.sqlite.exec(compiledQuery.sql, compiledQuery.parameters.map(_ => dialect.convert(_)) as SQLiteType[])
        const rows = results.map(result => result.values.map(_ => zipObject(result.columns, _) as unknown as O))[0] ?? []
        const numUpdatedOrDeletedRows = BigInt(await dialect.sqlite.changes())
        return {
          rows: rows.map(row => {
            // if (isInt)
            return Object.fromEntries(Object.entries(row as any).map(([k, v]) => {
              if (k === "myint8arrayfield") {
                const i: Int8Array = v as Int8Array
                // if i console.log the value here, it's still an Int8Array
                // does not work return [k, i] as const
                // DOES work return [k, Array.from(i)] as const
                // does not work return [k, new Uint8Array(i)] as const
              }
              return [k, v] as const
            }))
          }) as any,
          numUpdatedOrDeletedRows
        }
      }
```

**Comment by koskimas** [comment]
Kysely does no conversions. See the db driver's docs.

**Comment by midwesterntechnology** [comment]
> Kysely doesn't touch the data in any way whatsoever. It just passes it through.
> 
> If you use the debugger to step through the code, you'd immediately see where the conversion happens. Definitely faster than writing this issue.
> 
> My guess: you have a pair of JSON.stringify and JSON.parse somewhere.
> 
> Maybe you are using some plugin?

Strange. No plugins, I thought maybe Kysely was serializing somewhere because the driver was giving me the right type. I'll go through and debug. Thanks.

**Comment by midwesterntechnology** [comment]
@koskimas I figured it out - it is Kysely, but, it's also a plugin (the built in CamelCasePlugin - thought I had tested without it).

```
function canMap(obj) {
    return (0, object_utils_js_1.isObject)(obj) && !(0, object_utils_js_1.isDate)(obj) && !(0, object_utils_js_1.isBuffer))(obj);
}
```

Since Int8Array/Uint8Array/etc passes the isObject test it tries to map the keys.

Might make sense to add another negative condition here. ArrayBuffer.isView? Not sure what's most compatible.
