### ISSUE TITLE
Separate types for insert & select--potential sponsorship

### ISSUE THREAD

**Issue by codetheweb** [koskimas/kysely#196]
Thanks for this great library!

At [Seam](https://www.getseam.com/) we use Knex but aren't very happy with how badly it's typed. I started building an [extremely similar library](https://github.com/seamapi/quackatos) to Kysely, but it became a lower priority once I came across Kysely.

We tried Kysely on a small project and it worked really well. 

One of the downsides that we saw was not having separate types for insert and select (which the generated types that we use with Knex currently have). I saw there was some [previous discussion](https://github.com/koskimas/kysely/issues/5) about something like this, but was wondering if you'd consider it again. While it does add type complexity, it didn't seem too bad when I was implementing it in my library above.

As far as the type generation goes, [Zapatos](https://jawj.github.io/zapatos/) generates extremely robust types with different interfaces for select, where, and insert (and a bunch of other metadata as well like indices)--seems like we could get the best of both worlds by combining Kysely and Zapatos.

Seam would be happy to sponsor you for your work towards this if you're interested. :)

**Comment by igalklebanov** [comment]
Hey!

> One of the downsides that we saw was not having separate types for insert and select (which the generated types that we use with Knex currently have). I saw there was some [previous discussion](https://github.com/koskimas/kysely/issues/5) about something like this, but was wondering if you'd consider it again. While it does add type complexity, it didn't seem too bad when I was implementing it in my library above.

Have a look at these docs and let me know if that's what you had in mind..

https://koskimas.github.io/kysely/types/ColumnType.html

**Comment by igalklebanov** [comment]
> As far as the type generation goes, [Zapatos](https://jawj.github.io/zapatos/) generates extremely robust types with different interfaces for select, where, and insert (and a bunch of other metadata as well like indices)--seems like we could get the best of both worlds by combining Kysely and Zapatos.

Speaking of type generation, there's a 3rd party package you should have a look at..

https://github.com/RobinBlomberg/kysely-codegen

**Comment by koskimas** [comment]
> One of the downsides that we saw was not having separate types for insert and select (which the generated types that we use with Knex currently have). I saw there was some https://github.com/koskimas/kysely/issues/5 about something like this, but was wondering if you'd consider it again. While it does add type complexity, it didn't seem too bad when I was implementing it in my library above.

As @igalklebanov mentioned, this has been implemented through the `ColumnType` helper. If you want to use separate interfaces instead, there's an easy way to get one from the other

```ts
interface PersonInsert {
  first_name: string
}

interface PersonSelect {
  id: string
  first_name: string
  created_at: Date
}

interface PersonUpdate {
  first_name: string
}

type Merge<I, S, U> = {
  [K in keyof I | keyof S | keyof U]: ColumnType<
    K extends keyof I ? I[K] : never,
    K extends keyof S ? S[K] : never,
    K extends keyof U ? U[K] : never,
  >
}

type T = Merge<PersonInsert, PersonSelect, PersonUpdate>
```

> As far as the type generation goes, [Zapatos](https://jawj.github.io/zapatos/) generates extremely robust types with different interfaces for select, where, and insert (and a bunch of other metadata as well like indices)--seems like we could get the best of both worlds by combining Kysely and Zapatos.

Type generation is provided by the third party package @igalklebanov mentioned.

> Seam would be happy to sponsor you for your work towards this if you're interested. :)

Thank you for the offer, but I won't accept any money for my OSS work. OSS for me is a way to do something I enjoy without the stress of filling somebody else's expectations. It's the counterweight for my work.

**Comment by codetheweb** [comment]
Thank you for the response.

We did evaluate Kysely about a month ago, so it's possible that stuff changed or we just originally misread the documentation. In any case, `ColumnType` seems like it should solve our problem. Appreciate the help!
