### ISSUE TITLE
How to define UUID generated type within a table interface

### ISSUE THREAD

**Issue by aoloo** [koskimas/kysely#197]
I am unsure if this is supported or if my implementation is incorrect. But I am looking to achieve something like this. 

model
```
interface User {
  id: Generated<UUID>;
}
```

DB write schema 
```
.addColumn("id", "uuid", (col) =>
      col.primaryKey().defaultTo(sql`gen_random_uuid()`)
    )
```

**Comment by igalklebanov** [comment]
It is supported and [tested](https://github.com/koskimas/kysely/blob/master/test/node/src/schema.test.ts#L59-L61).

**Comment by aoloo** [comment]
How would I define a UUID generated type within the interface?

**Comment by koskimas** [comment]
The `pg` driver returns `UUID` fields as strings --> you need to use `string` as the type in the interface.

**Comment by igalklebanov** [comment]
Kysely is just a query builder, we do not define data types.

A uuid column should be defined as a `string`. You can wrap it with `ColumnType`/`Generated`/`GeneratedAlways`. In your use case, `Generated<string>` (allows to not provide a value when inserting) or `GeneratedAlways<string>` (prevents providing a value when inserting/updating -- read-only).

You can also define a uuid branded/opaque type instead. This resource should help: https://leebyron.com/til/opaque-types/

**Comment by aoloo** [comment]
@igalklebanov, thank you for the help.
