### ISSUE TITLE
CustomType with string values

### ISSUE THREAD

**Issue by nbabaka** [koskimas/kysely#198]
Hello, I have custom type in DB (postgres)
```
  await db.schema
  .createType('platform')
  .asEnum(['iOS', 'Android'])
  .execute()
```

and interface:

```
enum platform {
    iOS = 'iOS', 
    Android = 'Android'
}

interface Database {
    version: {
      id: Generated<number>;
      platform: platform;
```

but in the INSERT query it's STRINGVALUE -

```
  .insertInto("version")
  .values({
    platform: plat(platform.Android),
```

`ERROR: column "platform" is of type platform but expression is of type character varying`

How to change type for string ENUM?

Thank you

**Comment by igalklebanov** [comment]
Hey 👋 

You need to cast value to the relevant enum type.

Try this..

```ts
import { sql } from 'kysely'

db.insertInto("version")
  .values({
    platform: sql<platform>`${platform.Android}::platform`,
```

let me know if it worked for you..

**Comment by koskimas** [comment]
For this reason, and some others, I don't usually use postgres enums. I create an "enum table" instead:

```ts
db.createTable('platform')
  .addColumn('platform', 'text', col => col.primaryKey())

db.createTable('version')
  .addColumn('platform', 'text', col => col.references('platform.platform')

db.insertInto('platform')
  .values([{ platform: 'android' }, { platform: 'iOS' }])
```

**Comment by koskimas** [comment]
We could provide a `cast` function to help this, but the syntax wouldn't be much better

```ts
platform: cast(sql.value(platform.Android), 'platform')
```

Probably the cleanest solution is to create your own helper like this:

```ts
function platform(platform: platform): RawBuilder<platform> {
  return sql`${platform}::platform`
}
```

**Comment by luap2703** [comment]
@koskimas would it be somehow possible to flag all enums during the initialization of kysely and then automatically wrap all enum-inputs during runtime with such wrapper (behind the scenes)?

Our (exemplary) use case is as follows:
1. We define the db schema in Prisma
2. We generate kysely code from the Prisma schema (using the awsome prisma-kysely extension) (and unfortunately use Postgresql enums heavily)
3. We get quite a lot of runtime errors as the enums are correctly typed, but not cast

If it would somehow be possible to mark/classify all enums as such we could prevent this issue.

Anyway, thanks again for the great work on this library!!
