### ISSUE TITLE
camelcase？

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#2]
any plan to add camelcase support?

**Comment by koskimas** [comment]
Yep. I'll add a plugin interface and implement a camelCase conversion as a plugin.

**Comment by koskimas** [comment]
However, the conversion will be done for the SQL as well as the return value, as they are defined using the same interfaces. For example, if you have a table `person_table` with columns `id` and `first_name`, the conversion would work like this:

```ts
interface Person {
  id: string
  firstName: string
}

interface Database {
  personTable: Person
}

const db = new Kysely<Database>(...)

await db.selectFrom('personTable').select('id').where('firstName', '=', 'Sami')
```

So __EVERYTHING__ needs to be converted to camelCase by the plugin, or else the type system won't work. Kysely won't allow the return value column names to be different from the ones used in the queries.

**Comment by xiaoyu-tamu** [comment]
what's the generated sql for this query?

```ts
await db.selectFrom('personTable').select('id').where('firstName', '=', 'Sami')
```

will the above query build to this sql?

```sql
select id from person_table where first_name = 'Sami' 
```

**Comment by koskimas** [comment]
Yes.

**Comment by xiaoyu-tamu** [comment]
that would be nice!

**Comment by koskimas** [comment]
@xiaoyu-tamu I just added the first version of the plugin interface and a plugin called [CamelCasePlugin](https://koskimas.github.io/kysely/classes/CamelCasePlugin.html)

**Comment by xiaoyu-tamu** [comment]
will try it later today.

**Comment by xiaoyu-tamu** [comment]
Hi, @koskimas 

I just tried it and it works as expected
