### ISSUE TITLE
.executeTakeFirstOrThrow() returns null instead of throwing

### ISSUE THREAD

**Issue by 68kHeart** [koskimas/kysely#205]
# Description

When executing a `SELECT` query with `.executeTakeFirstOrThrow()`, it returns `null` if the result set is empty instead of throwing an exception.

# Environment

| Name           | Version |
|:---------------|:--------|
| macOS          | 13.0    |
| Node           | 16.17.0 |
| npm            | 8.15.0  |
| Kysely         | 0.22.0  |
| Kysely Codegen | 0.7.4   |
| MySQL          | 5.7.38  |
| mysql2         | 2.3.3   |

# Additional Details

- Query was verified to return `[]` with `.execute()`
- Query was verified to return `undefined` with `.executeTakeFirst()`
- Query was verified to throw a `NoResultError` exception when the connection details were invalid
- Return type from `.executeTakeFirstOrThrow()` does not reflect the potential for `null`
- Issue occurs when using `min` and `max` aggregate functions; potentially others
- Query verified to throw a `NoResultError` when selecting columns without using aggregate functions

**Comment by igalklebanov** [comment]
Interesting. Are you using any plugins?

**Comment by koskimas** [comment]
I'm guessing it's a third party dialect or a plugin. See the code here https://github.com/koskimas/kysely/blob/3f91374cee3a0f67cc395c7ab583a12a154716b1/src/query-builder/select-query-builder.ts#L1644

**Comment by koskimas** [comment]
Haha, another way this could fail is if you pass in an error constructor that returns a null. Gotta love javascript

**Comment by 68kHeart** [comment]
In Kysely? No, I'm only using it with the built-in MySQL adapter; not even using the CamelCasePlugin yet. (Just realized I should probably include the `mysql2` version, too!)

**Comment by igalklebanov** [comment]
`avg`, `max`, `min` & `sum` are nullable when they don't have rows to work with.

In a future release you'll be able to opt-in to hinting the'yre nullable, and/or wrap them with `coalesce`.

**Comment by koskimas** [comment]
Yep, that query always returns one row, even if the result from which `max` is taken is empty. That's how SQL works. As mentioned, we can improve by making the aggregated values billable, but it won't change this behavior.

**Comment by 68kHeart** [comment]
Cool, thanks for looking into it and for the context around the issue!
