### ISSUE TITLE
How to insert json data to jsonb column

### ISSUE THREAD

**Issue by nbabaka** [koskimas/kysely#209]
Hello,

I have Postgres DB and a table with jsonb-type field in it.
I need to insert a row to it and can not do it with error "Could not serialize value"

```
    settings: {
      id: Generated<number>;
      application_id: number;
      data: Record<string, any>
      created_at: Generated<Date>;
      updated_at: Generated<Date>;
    }
```
```
    await db.insertInto('settings')
    .values([{
        application_id: 1,
        data: {
            'test': 'test',
            'com': 'test'
        }
    }]).execute()
```

Is any way to do it with kysely?

Thank you!

**Comment by igalklebanov** [comment]
Hey :wave:

There is currently no built-in way to do it.

Try [this](https://github.com/koskimas/kysely/blob/master/test/node/src/postgres-json.test.ts#L41-L66).

**Comment by nbabaka** [comment]
@igalklebanov Thank you!

**Comment by acamaral** [comment]
Hello,

I tried 

> Hey 👋
> 
> There is currently no built-in way to do it.
> 
> Try [this](https://github.com/koskimas/kysely/blob/b012bd4115c267a08a472a74c432722027199d0c/test/node/src/postgres-json.test.ts#L41-L66).

Hello, @igalklebanov and everybody else.

I tried the above solution, but it didn't work. So I tested the following and now it works.

```typescript
function json<T> (object: T): RawBuilder<T> {
  return sql`cast (${JSON.stringify(object)} as jsonb)`
}
```

**Comment by divmgl** [comment]
To anyone running into this issue in Bun, I'm noticing that this https://github.com/kysely-org/kysely/issues/209#issuecomment-1306187965 will cause Kysely to make a query that stores the string representation of the object, not the object itself.

I was able to fix this by removing `JSON.stringify`:

```tsx
sql`cast(${response}) as jsonb)`
```

Now the object is stored correctly. Cheers.
