### ISSUE TITLE
Support multiple column `ALTER TABLE`.

### ISSUE THREAD

**Issue by igalklebanov** [koskimas/kysely#217]
raised by steebee on discord.

upon discussion we've agreed to add this.

@koskimas added that we should throw an error on dialects that don't support this (we need another flag in `Adapter`).

**Comment by naorpeled** [comment]
Hey @igalklebanov,
may I be assigned to this issue? 🙏 

Thanks!

**Comment by igalklebanov** [comment]
Sure.. thanks!
