### ISSUE TITLE
Is the compile step necessary?

### ISSUE THREAD

**Issue by steida** [koskimas/kysely#22]
Is there a design decision I'm not aware of that requires chainable functions API?
It seems typed SQL should be possible with Template Literal Types only.

https://twitter.com/c_pick/status/1307433762914009090
https://github.com/codemix/ts-sql

There is nothing wrong with the current API, I am just curious since I am using such "selectors". The problem with "selector" is that it requires React useCallback Hook because the callback is not referentially transparent. So I am asking myself whether ts-sql is possible with kysely requirements.

```ts
const { data } = useContactsDB(
  (db) => db.selectFrom('contact').selectAll().execute(),
);
```

**Comment by koskimas** [comment]
You can't get autocompletion with using only template literals. The current API is very much a design choice. Also, using only template literals would result in such insane type wankery, that nobody would be able to ever join the project as a contributor 😄
