### ISSUE TITLE
Decouple migrations from storage

### ISSUE THREAD

**Issue by moltar** [koskimas/kysely#23]
Current migration solution assumes a list of files exists on disk.

This can be problematic when bundling the project into a single file (e.g. using esbuild or webpack). Bundler follows `import` or `require` statements and combines the code into a single file. Since we are using file system reads, those files will not be bundled, as bundlers do not follow `fs.read*` operations, or even dynamic `import` or `require` statements.

The solution, I think, is to decouple the migrations solution into a common interface (e.g. `MigrationProvider`) that returns an array of migrations.

```ts
interface MigrationProvider {
  migrations: Promise<Migration[]>
}
```

Each concrete implementation would then implement it and we can have interchangeable migration loaders.

Current solution would become `FileSystemMigrationProvider`:

```ts
class FileSystemMigrationProvider implements MigrationProvider {
  async migrations(): Promise<Migration[]> {
    // return fs.read()...
  }
}
```

For bundling use cases, there would be another one:

```ts
// maybe a bad name, but best I can think of at the moment
class InMemoryMigrationProvider implements MigrationProvider {
  constructor(private readonly migrations: Migration[]) {}

  async migrations(): Promise<Migration[]> {
    return Promise.resolve(this.migrations)
  }
}
```

Which will then simply import all migrations and supply them into the `InMemoryMigrationProvider` constructor. Which will then force the bundler to consider these files and bundle them into a single file.

---

TypeORM follows a similar pattern, and [allows providing an array of migration classes as a config option](https://typeorm.io/#/connection-options/common-connection-options).

**Comment by koskimas** [comment]
Current migrations don't actually assume a list of files. You can either pass in a file path OR a list of migration objects with up and down methods.

**Comment by koskimas** [comment]
I'll add this example to the documentation:

```ts
await db.migration.migrateToLatest({
  migration1: {
    async up(db: Kysely<any>): Promise<void> {
      ...
    },

    async down(db: Kysely<any>): Promise<void> {
      ...
    }
 },

 migration2: {
    async up(db: Kysely<any>): Promise<void> {
      ...
    },

    async down(db: Kysely<any>): Promise<void> {
      ...
    }
 },

 ...
))
```

**Comment by koskimas** [comment]
This is the implementation of `migrateToLatest`:

```ts
  async migrateToLatest(
    migrationsOrFolderPath: Record<string, Migration> | string
  ): Promise<void> {
    await ensureMigrationTablesExists(this.#db)

    const allMigrations = await this.#getAllMigrations(migrationsOrFolderPath)
    await this.#migrateToLatest(allMigrations)
  }

  async #getAllMigrations(
    migrationsOrFolderPath: Record<string, Migration> | string
  ): Promise<Record<string, Migration>> {
    return isString(migrationsOrFolderPath)
      ? await readMigrationsFromFolder(migrationsOrFolderPath)
      : migrationsOrFolderPath
  }
```

**Comment by moltar** [comment]
Ah, great! A list of migration objects is exactly what I was thinking. Thank you.
