### ISSUE TITLE
Bug: sqlite introspection does not detect autoincrement column when sql contains newlines

### ISSUE THREAD

**Issue by tobiasfoerg** [koskimas/kysely#235]
```typescript
const autoIncrementCol = createSql[0]?.sql
      ?.split(/[\(\),]/)
      ?.find((it) => it.toLowerCase().includes('autoincrement'))
      ?.split(/\s+/)?.[0]
      ?.replace(/["`]/g, '')
```
https://github.com/koskimas/kysely/blob/2c49bae555505d347e73ded4cafc0f5dc7279426/src/dialect/sqlite/sqlite-introspector.ts#L68:L72

given the following sql:
```sql
CREATE TABLE "users"
(
    "id"         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name"       TEXT     NOT NULL
)
```

the result of find the autoincrement row is:   `\n    "id"         INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT` 
after split on `whitespace` the first item inside the array is `""` instead of `""id""`

**Comment by igalklebanov** [comment]
Good catch! Can confirm this is happening with given example and is fixed by #236.
