### ISSUE TITLE
Log the query?

### ISSUE THREAD

**Issue by spa5k** [koskimas/kysely#24]
Hey, is there a way to log the generated query?

I tried this but it did not printed out the queries.

```ts
export const db = new Kysely<ModelTypeMap>({
  dialect: new PostgresDialect({
    host: "localhost",
    database: "postgres",
    password: "postgres",
    user: "postgres",
    log: (message) => {
      console.info(message);
    },
  }),
});

// Output

/*
checking client timeout
connecting new client
new client connected
pulse queue
no queued requests
[
  {
    id: 2,
    slug: 'a',
    name: 'a',
    last_updated: 2021-11-29T11:51:27.581Z,
    thumbnail_url: 'aa',
    default_source: 'a',
    status: 'ENABLED'
  }
]
remove idle client
*/
```

**Comment by koskimas** [comment]
There's currently no built-in way to log queries in Kysely. The parameters the `PostgresDialect` takes are passed directly to the [pg module](https://node-postgres.com/). The only your code works is if `pg` supports that log. And if it doesn't, it's a bug in `pg`.

You can get the compiled sql like this for any query:

```ts
const sql = db
  .selectFrom('foo')
  .where(...)
  .orderBy(...)
  .selectAll()
  .compile()

console.log(sql)
```

I'll probably add some way to debug queries soon.

**Comment by koskimas** [comment]
What's the ideal API for logging queries in your opinion? Should it log the query outputs too? Do you want a global debug setting as well as a way to log individual queries?

**Comment by spa5k** [comment]
Have you seen how Prisma does it, that looks pretty good, also i dont think there is any need for logging the output, only having a query logger is good enough, global setting should be good enough, individual query logging isnt worth it imo.

**Comment by koskimas** [comment]
[Prisma logging](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) has a bunch of features. It would be overkill to copy all of that. What in particular do you need?

**Comment by elderapo** [comment]
Logging all queries, slow queries, failed queries maybe would be a good start :)

**Comment by koskimas** [comment]
I released a new version 0.9.4 with [very minimal query logging](https://koskimas.github.io/kysely/interfaces/KyselyConfig.html#log).

You can now give the `log: ['query']` option for the `Kysely` constructor and it will log _all_ queries and their durations.

**Comment by AzSiAz** [comment]
An option to log request param could be useful for debug

**Comment by koskimas** [comment]
@AzSiAz 0.11.3 now supports a custom logger function:

```ts
const db = new Kysely<Database>({
  dialect: new PostgresDialect(postgresConfig),
  log(event): void {
    if (event.level === 'query') {
      console.log(event.query.sql)
      console.log(event.query.parameters)
    }
  }
})
```

**Comment by koskimas** [comment]
I'll consider this implemented for now. Feel free to open issues if you want me to extend the logging somehow.

**Comment by JS-GitRepo** [comment]
This was very helpful! However I had a very hard time finding any info on logging in the docs. Would be awesome if some of this info were mapped there

**Comment by elderapo** [comment]
@JS-GitRepo You're more than welcome to create a PR with docs update.

**Comment by jetaggart** [comment]
I'm trying to get a request id in the logging statements. Any thoughts on how to accomplish this without using AsyncLocalStorage/async_hooks (perf hit too great)? I could initialize the Kysely object on every request and put it in context but that also increases memory pressure. Any guidance would be awesome, thanks!

**Comment by nikeee** [comment]
I'm facing the issue of using Sentry with Kysely.

Sentry's API allows for this:
```ts
const result = Sentry.startSpan({ name: "Important Function" }, () => {
  return expensiveFunction();
});
```
or
```ts
const span1 = Sentry.startInactiveSpan({ name: "span1" });
someWork();
span1.end();
```
Now, I want to log every query. I tried these approaches:

### 1. Using the log() function

```ts
const db = new Kysely<Database>({
  dialect: ...,
  log: (event) => {
    if (event.level === "query") {
	  const startTime = Date.now() - event.queryDurationMillis;
      Sentry.startInactiveSpan({ name: event.query.sql, op: "db.query", startTime }).end();
    }
  },
});
```
This approach seems hacky, since the queryDurationMillis might not be that accurate when computing the startTime manually.


### 1. Using a plugin

```ts
export default class SentryLogPlugin implements KyselyPlugin {
  spans = new Map<PluginTransformQueryArgs["queryId"], Span>();

  transformQuery(args: PluginTransformQueryArgs) {
    const span = startInactiveSpan({ name: "db-query", op: "db.query" });
    this.spans.set(args.queryId, span);
    return args.node;
  }

  async transformResult(args: PluginTransformResultArgs) {
    const span = this.spans.get(args.queryId);
    if (span) {
      this.spans.delete(args.queryId);
      span.end();
    }
    return args.result;
  }
}
```

While this works, it doesn't have the ability to log the query without the values (`event.query.sql`). It also seems hacky because the plugins are made for data transformation and not for logging.

What is the correct way of approaching this?

**Comment by alonroth** [comment]
@nikeee did you find a solution for it?

**Comment by nikeee** [comment]
@alonroth i used the first hack mentioned in my response:
```ts
startInactiveSpan({
    name: e.query.sql,
    op: "db.query",
    startTime: new Date(Date.now() - info.duration),
    onlyIfParent: true,
}).end();
```
