### ISSUE TITLE
Question: How do transaction management works in kysely?

### ISSUE THREAD

**Issue by RIP21** [koskimas/kysely#248]
I wasn't able to find any examples here. 

The only mention of Transaction is in API reference and it's still unclear how to use it etc.

Is there a plan to add such docs at some point? As for now, I'm unsure when it opens and closes transactions TBH :)

Thanks!

**Comment by igalklebanov** [comment]
Hey 👋 

> The only mention of Transaction is in API reference and it's still unclear how to use it etc.

What page did you land on?

> Is there a plan to add such docs at some point? As for now, I'm unsure when it opens and closes transactions TBH :)

Description and examples can be found [here](https://koskimas.github.io/kysely/classes/Kysely.html#transaction), and when using kysely in your IDE.

**Comment by RIP21** [comment]
I landed on the GitHub readme, then went to TS generated one here https://koskimas.github.io/kysely/index.html 
And for the search, I simply used my Ctrl + F :)

Totally forgot to check the repo files themselves to land on examples and recipes  :)
I see that I could've landed on recipes from README too if I would read it more carefully, but they all are still missing an answer on transactions.

Ok, now I see that I was almost there :) I haven't scrolled `Transaction` docs long enough to get to `transaction` member docs to see usage example :)

**Comment by koskimas** [comment]
There's a search in the docs. At the top, you know, the thing that looks like a search bar.
