### ISSUE TITLE
Feature Request: clear 

### ISSUE THREAD

**Issue by wirekang** [koskimas/kysely#249]
It would be nice to clear the part of previous node. In knex, there is a `clear` method.

```ts
const query = knex("Table").select("a","b") // SELECT a, b FROM Table
query.clear("select")
query.select("a") // SELECT a FROM Table
```

This is a useful feature for reusing parts of queries.

**Comment by koskimas** [comment]
Unlike Knex, Kysely is completely immutable. You can do this:

```ts
const query = db.selectFrom("Table")
const query2 = query.select(["a", "b"])
// This only has the selection `a`
const query3 = query.select("a")
```

**Comment by wirekang** [comment]
@koskimas This feature is useful whether it is immutable or not.

For example, I'm using [goqu](https://github.com/doug-martin/goqu) when building SQL in Go, and it's QueryBuilder is immutable and has [Clear...](https://pkg.go.dev/github.com/doug-martin/goqu#Dataset.ClearSelect).



This is my use-case with knex. I have to count the total rows without pagenation.

```ts
export async function countKnex(b: Knex.QueryBuilder): Promise<number> {
  const query = b
    .clone()
    .clear("select")
    .clear("limit")
    .clear("offset")
    .clear("order")
    .select(knex.raw("COUNT(*) OVER() as cnt"));
  const [res] = await query;
  if (!res) {
    return 0;
  }
  return res.cnt;
}
```

**Comment by koskimas** [comment]
That's a good example. We need separate `clearSelect()`, `clearLimit()` etc. methods instead of a `clear(what)` method. For example `clearSelect()` will change the query builder type. Some clear methods like `clearJoin()` shouldn't be implemented because of what it would do to the types. Removing a join and keeping a selection from that table will mess up the types (and the query too).

**Comment by thelinuxlich** [comment]
The use case is not interesting in Kysely because you could have a query1 variable with most of the query, a query2 reusing query1 with limit,offset and order and a query3 replacing the select with count.

**Comment by thelinuxlich** [comment]
You'd have a helper that accepts a query instance and returns it adding .limit().offset().order()

**Comment by wirekang** [comment]
> You'd have a helper that accepts a query instance and returns it adding .limit().offset().order()

It's not that simple. If the logic was simple, there is no need to use query builder. The helper will looks like:

```ts
const { merged, count } = countHelper(
   q => {
      // logics with select, order, offset, limit
      return q
   },
   q  => {
       // logics with join, where, ...etc
       return q
    }
)

const result = merged.execute()
const cnt = count.execute()
```

It there is a way to merge two SelectQueryBuilder in kysely, the helper function be maded. But adding `clear` method is a better solution.

**Comment by thelinuxlich** [comment]
I was thinking of something like

```ts
import { ExpressionBuilder, SelectExpression, sql } from "kysely";
export default <DB, TB extends keyof DB, S extends SelectExpression<DB, TB>>(
	eb: ExpressionBuilder<DB, TB>,
        field: S, 
        sortField: S,
        sortDirection = "asc",
        limit = 10,
        offset = 1,
) => {
	return eb.select(qb => qb.fn.count<number>(field).as("count")).limit(limit).offset(offset).orderBy(sortField, sortDirection)
};

// usage
query.call(qb => countHelper(qb, "id", "created_at"))
```
