### ISSUE TITLE
Missing pg array operator (&&)

### ISSUE THREAD

**Issue by AzSiAz** [koskimas/kysely#25]
`&&` operator seem to be missing in `where` 

Can still use `raw('&&')` so not a real problem

Also any plan to add `andWhere` and make it take an array for non-dynamique query ?
Where and querybuilder callback is great but kind of verbose for simple case

Thanks for the lib 👍

**Comment by koskimas** [comment]
I'll add the `&&` operator asap.

I don't understand the second question about `andWhere`? You can call `where` multiple times and `and` is added between them automatically (unless you use orWhere).

**Comment by koskimas** [comment]
I released a new version with the `&&` operator.

**Comment by AzSiAz** [comment]
Thanks for the quick update

🤦‍♂️ , sorry seem like I used an `orWhere` in my query...

**Comment by AzSiAz** [comment]
In migrating some query from Prisma, to use ts_vector and generated column, I see two more missing [operator](https://www.postgresql.org/docs/10/functions-textsearch.html) `@@` and `<->`

**Comment by koskimas** [comment]
Thanks! I added the rest of the missing operators from that page.

**Comment by AzSiAz** [comment]
Thanks ! 😄
