### ISSUE TITLE
add `count(*)` & `count(t1.*)` support.

### ISSUE THREAD

**Issue by igalklebanov** [koskimas/kysely#250]
Currently the following syntax is not supported:

```sql
select count(*) as count from t1;
select count(t1.*) as count from t1 inner join t2 on t1.id = t2.t1_id;
```

This should probably be added as `FunctionModule.countAll(table?)`.

**Comment by koskimas** [comment]
There's `count(*)` sized gap in my sql knowledge. When is that syntax useful compared to `count(column)` or `count(table.column)`?

**Comment by noppa** [comment]
`count(column)` doesn't count nulls, which is often not what you want if you are interested in the amount of rows. You can usually go around this by using non-nullable column like id, but maybe your table or subquery doesn't have such a column.

**Comment by koskimas** [comment]
Thanks! Let's add these then 👍

**Comment by Nithur-M** [comment]
is this added? how to access it?

**Comment by elitan** [comment]
> is this added? how to access it?

Yes, you can use it like this:

```ts
    const { count } = await db
      .selectFrom("jobs")
      .select(db.fn.countAll().as("count"))
      .executeTakeFirstOrThrow();
```

**Comment by capaj** [comment]
THis should be added to the docs

**Comment by igalklebanov** [comment]
@capaj @vikiival submit a PR. 🤷

**Comment by capaj** [comment]
It's a bit verbose. Why us there no shorthand like 

```ts
const { count } = await db
  .selectFrom("jobs").countAll()
```

?

**Comment by capaj** [comment]
at the second glimpse that would take the API too far from the SQL underneath. Sorry for dumb questions, knex.js might have ruined me for eternity.
