### ISSUE TITLE
Infer database types from migration code?

### ISSUE THREAD

**Issue by jeremyjacob** [koskimas/kysely#252]
I think it would be cool and make kysely a more competitive alternative (to Prisma) if the database types could be directly inferred from the migration schema, Zod-style. This would eliminate the need for generation libraries, and provide instant feedback to the developer.

So with something like this
```js
await db.schema.createTable("payment")
	.addColumn("id", cuid)
	.addColumn("created", "timestamp")
	.addColumn("updated", "timestamp")
	.addColumn("status", "text")
	.addColumn("amount", "int4")
	.addColumn("description", "text")
	.execute();
```
we could infer the equivalent of the type
```ts
type Payment = {
  amount: number | null;
  created: Date | null;
  customer_id: string | null;
  description: string | null;
  id: string | null;
  status: string | null;
  updated: Date | null;
}
```

I'm not sure this is possible with the current API, but maybe an alternative object-based API could allow for it? This might be out of scope for what kysely is aiming for, but thought I'd throw it out there.

Cheers

**Comment by koskimas** [comment]
This is been answered multiple times.

**Comment by koskimas** [comment]
And kysely is not trying to be competitive with Prisma. We don't get paid, unlike people at Prisma. This is just some code we wrote and thought other people might find useful. Use it if you like. If you don't, find something else.

**Comment by jeremyjacob** [comment]
Understood, I think it's a wonderful project. Sending many thanks for your work on it.
