### ISSUE TITLE
`IF NOT EXISTS` support for `CREATE INDEX` in SQLite

### ISSUE THREAD

**Issue by Azarattum** [koskimas/kysely#253]
[SQLite supports](https://www.sqlite.org/lang_createindex.html) `IF NOT EXISTS` when creating a new index, however `Kysely` doesn't give an option to add the modifier. It should look something like:
```ts
db.schema
  .createIndex(name)
  .ifNotExists() // Property 'ifNotExists' does not exist on type 'CreateIndexBuilder'.
  .on(table)
  .columns(columns);
```

**Comment by koskimas** [comment]
I think all built-in dialects supports this. Let's add it.

**Comment by igalklebanov** [comment]
PostgreSQL does support it, MySQL doesn't. 🤷

**Comment by koskimas** [comment]
Crap
