### ISSUE TITLE
Support Postgres generated column

### ISSUE THREAD

**Issue by AzSiAz** [koskimas/kysely#26]
I didn't found a way to use Postgres generated column or to alter a table to add a generated column (no view/materialized view either)

My use case is storing a tsvector representation of another column to allow faster searching with a gin index

[Link](https://www.postgresql.org/docs/12/ddl-generated-columns.html) to the doc just in case

**Comment by koskimas** [comment]
You can always run raw queries in migrations using `db.raw`. Views could be one of the next things to add. I've never used generated columns or heard anyone using them. But I'll see if it's easy to add support for those too.

**Comment by AzSiAz** [comment]
True, I could always create the table and add a manual alter table after 🤔 

Generated column are quite new (PG 12) and to be honest the only time I saw them used is [here](https://www.postgresql.org/docs/current/textsearch-tables.html#TEXTSEARCH-TABLES-INDEX)

**Comment by koskimas** [comment]
0.9.9 version now has `createView` and `dropView` methods in the schema module.

**Comment by koskimas** [comment]
0.10.0 also supports materialized views. There's a couple of breaking changes in 0.10.0 https://github.com/koskimas/kysely/releases

**Comment by koskimas** [comment]
Generated columns are now also supported in master. Not released yet. You can use it like this:

```ts
db.schema
  .createTable('person')
  .addColumn('full_name', 'varchar(255)',
    (col) => col.generatedAlwaysAs("concat(first_name, ' ', last_name)").stored()
  )
  .execute()
```

**Comment by AzSiAz** [comment]
Thanks for those 3 extremely quick update, I will try to test these new migration as soon as I can

To be honest I had to replace some prisma query for more optimized query and working with Kysely as been fantastic so far, so thank you ☺️
