### ISSUE TITLE
InsertQueryBuilder.values() not making type error.

### ISSUE THREAD

**Issue by wirekang** [koskimas/kysely#266]
At first, I think it's playground error, but IDE reporduces same problem.

You can pass any value to `values`.
```ts
db.insertInto("user").values(0)
db.insertInto("user").values("")
db.insertInto("user").values(true)
db.insertInto("user").values(new URLSearchParams())
```

If you wrap argument with array, you can also pass any value.
```ts
db.insertInto("user").values([0,0])
db.insertInto("user").values(["",""])
db.insertInto("user").values([true,false])
db.insertInto("user").values([new URLSearchParams(),new HTMLInputElement()])
```

[Playground](https://wirekang.github.io/kysely-playground/?i=-NKXPISVdIbHy28L3GUM)

```json
"dependencies": {
    "kysely": "^0.23.3",
    "typescript": "^4.9.4"
}
```

**Comment by wirekang** [comment]
I made [minimum reproducible repository](https://github.com/wirekang/kysely-issue-266)

**Comment by wirekang** [comment]
I'm use WebStorm. I found that when I open the project with VSCode, type error shows correctly.  Maybe this is JetBrains related problem.

**Comment by igalklebanov** [comment]
This is not happening for me..

![image](https://user-images.githubusercontent.com/14938291/210057238-e03886bb-7ec6-408b-a04f-0137ed59d7bd.png)

**Comment by igalklebanov** [comment]
WebStorm is notoriously weird with typescript. Some of my co-workers use it, and there were a few times it didn't error on things that immediately error with VS Code (if the language server didn't crash haha).

Maybe it uses a non-strict `tsconfig` other than your project's one?

**Comment by wirekang** [comment]
> Maybe it uses a non-strict tsconfig other than your project's one?

This is correct! I think VS Code has default tsconfig settings like `strict: true`, but playground and WebStrom has not. If I add tsconfig and set strict to true, all problem is gone. Thank you!!
