### ISSUE TITLE
add `DeleteQueryBuilder.returningAll(table)` overload.

### ISSUE THREAD

**Issue by igalklebanov** [koskimas/kysely#268]
Merge of #241 introduced deletes with joined tables for filtering and returning in databases such as PostgreSQL. We support `returning *` but we don't offer `returning table.*` similar to `selectAll(table)`.

```ts
db.deleteFrom('t1').using('t2').returningAll('t2');
```

This is a simple addition of an overload of `DeleteQueryBuilder.returningAll` with a table as argument.

**Comment by anirudh1713** [comment]
Hi @igalklebanov, Can I take this on?

**Comment by igalklebanov** [comment]
@anirudh1713 Sure! @me on discord if you need help.
