### ISSUE TITLE
add `QueryCreator.deleteFrom([t1, t2, ...])` overload.

### ISSUE THREAD

**Issue by igalklebanov** [koskimas/kysely#269]
Merge of #241 introduced deletes with joined tables for filtering in databases such as MySQL. This is a real tease for consumers using such a database, as it supports deleting from multiple tables in a single `delete from` query by simply listing multiple tables after `from` clause.

```ts
db.deleteFrom(['t1', 't2']).where(...).execute();
```

This is an addition of an overload of `QueryCreator.deleteFrom` with an array of table references as argument. It should behave similarly to the multi-table variant of `QueryCreator.selectFrom`.

**Comment by KostyaTretyak** [comment]
By the way, for now `deleteFrom` with aliases works incorrectly:

```ts
await db
  .deleteFrom('t1' as any)
  .using('table1 as t1')
  .innerJoin('table2 as t2', ...)
  ...
```
As you can see, here is casting `'t1' as any` and it's not good.

And It is also desirable that the following form of deletion is also supported:

```sql
delete t1
from table1 as t1
inner join table2 as t2
  on...
```

Maybe Kysely can do something like this:

```ts
await db
  .from('table1 as t1')
  .delete('t1')
  .innerJoin('table2 as t2', ...)
  ...
```

**Comment by igalklebanov** [comment]
Hey @KostyaTretyak  👋 

We love the excitement! but can you please open separate issues for each individual problem/request?

>By the way, for now deleteFrom with aliases works incorrectly:
> ```ts
> await db
>   .deleteFrom('t1' as any)
>   .using('table1 as t1')
>   .innerJoin('table2 as t2', ...)
>   ```
> As you can see, here is casting 't1' as any and it's not good.

Of course its not good. 

1. Casting `as any` breaks inference.
2. `as t1` is only added to the context in `.using`, don't expect it to magically be part of `.deleteFrom`'s context. This is not how typescript works.

> And It is also desirable that the following form of deletion is also supported:
> ```sql
> delete t1
> from table1 as t1
> inner join table2 as t2
>   on...
> ```

This has already been requested @ #237.

**Comment by KostyaTretyak** [comment]
@igalklebanov, hi. I apologize if I said something off topic, but it seemed to me that my comment was talking about the same thing as in this issue.

**Comment by igalklebanov** [comment]
@KostyaTretyak not really. 

This issue is a specific feature request.

Your comment talked about a bug with current API and a whole different feature request.
