### ISSUE TITLE
Sqlite MATCH text search

### ISSUE THREAD

**Issue by jonluca** [koskimas/kysely#279]
If I have a sqlite db with a virtual table using fts like so:

```
CREATE VIRTUAL TABLE posts 
USING FTS4(title, body);
```

and then I try and reference it within Kysely

```
const statement = db
      .selectFrom("posts")
      .selectAll()
      .where("posts", "match", search)
      .limit(100);
```

I get a type error on match. 

The syntax for the query would look like

```
SELECT * 
FROM posts 
WHERE posts MATCH 'text' ;
```

Are match queries supported in kysely? 

Thanks in advance

**Comment by koskimas** [comment]
You can pass any operator using raw sql

```ts
where('posts', sql`match`, search)
```
