### ISSUE TITLE
Generate types from existing db

### ISSUE THREAD

**Issue by mmahalwy** [koskimas/kysely#28]
I'd assume something like https://www.npmjs.com/package/@rmp135/sql-ts would help with generating the types instead of writing them?

**Comment by koskimas** [comment]
What prevents you from using that library using `npx`? I agree something like that would be a nice feature, but does writing a simple interface per table really take a significant portion of the development time? I can only imagine it does if you are writing a very simple crud, and in that case, why not use one of the 100 projects that generate a crud from db?

**Comment by mmahalwy** [comment]
Nothing prevents. It was a suggestion!

**Comment by koskimas** [comment]
What I meant was, if that library already does what you need, why not use it to create the interfaces for Kysely? If it works, why would we need to copy paste the code to Kysely?

**Comment by martinblostein** [comment]
To be fair, if `sql-ts` really works, code would not have to to be copy pasted. Instead Kysely could include `sql-ts` as an optional dependency.

And there is a benefit beyond saving time: automatic generation prevent errors when creating the type interfaces.

**Comment by koskimas** [comment]
`sql-ts` has a CLI you can run using `npx` without installing anything locally.

**Comment by mmahalwy** [comment]
Yeah, they dont need to depend on each other. They can work in parallel where we simple import the types from the generated `sql-ts` file. 


```ts
import { Person, Pet, Movie } from './sql-ts-generated';

interface Database {
  person: Person
  pet: Pet
  movie: Movie
}
```

**Comment by martinblostein** [comment]
Sure, I was just saying that sql-ts could be integrated without copy and pasting code. If you don't want to go that route, no worries.
