### ISSUE TITLE
[CamelCasePlugin] Add option to disable transforming of JSON content

### ISSUE THREAD

**Issue by m4rvr** [koskimas/kysely#281]
When using the CamelCasePlugin, it also transforms the content of JSON fields.
It would be nice to have an option that disables that, so the contents remain in snake_case.

Discord thread for reference:
https://discord.com/channels/890118421587578920/890118421587578925/1063741659545882625

**Comment by igalklebanov** [comment]
@m4rvr this has been released.

You should check out the new type-safe JSON traversal features released in https://github.com/kysely-org/kysely/releases/tag/0.26.0.
