### ISSUE TITLE
Transient Error Retries

### ISSUE THREAD

**Issue by JonathanHopeDMRC** [koskimas/kysely#283]
Some other NPM packages that have similar aims like Slonik support retrying transactions/queries. I can't find anything about retries in the kysely docs. Is there any plan to add support for retries to kysely, or is there a recommended approach using third party packages?

Thanks!

**Comment by igalklebanov** [comment]
Hey 👋 

> Some other NPM packages that have similar aims like Slonik support retrying transactions/queries.

Slonik's aim seems to be `node-postgres` on steroids with some type-safety.
Kysely's aim is primarily to be a type-safe sql query builder. It also does other things like execution, migrations, etc.

> I can't find anything about retries in the kysely docs. Is there any plan to add support for retries to kysely

Not that I know of. Thanks for submitting this issue.
There is some intent to provide more fine-grained control with transactions @ #257, that might make it easier for consumers to implement their own retry mechanisms.

> is there a recommended approach using third party packages?

I'd probably try this [library](https://github.com/coveooss/exponential-backoff).

For query retries, I'd write a custom driver that overrides query execution like:

```ts
async override executeQuery<O>(compiledQuery: CompiledQuery): Promise<QueryResult<O>> {
  try {
    return await backoff(() => super.executeQuery(compiledQuery));
  } catch (error: unknown) {
    // ...
  }
}
```

**Comment by koskimas** [comment]
I think this is a little out of scope for a query builder. As @igalklebanov mentioned, a custom wrapper for your dialect is is only some tens of lines of code and would suit well in this situation.
