### ISSUE TITLE
docs(website): some links don't parses and other issues with docs

### ISSUE THREAD

**Issue by KostyaTretyak** [koskimas/kysely#286]
I found three cases where the `{@link tagName}` entry does not parse:

- `{@link selectAll}`
- `{@link sql}`
- `{@link $if}`

https://koskimas.github.io/kysely/classes/SelectQueryBuilder.html#select

**Comment by KostyaTretyak** [comment]
Also broken this example: https://koskimas.github.io/kysely/classes/SelectQueryBuilder.html#innerJoinLateral

~~~
```ts db.selectFrom('person') .innerJoinLateral( (eb) => eb.selectFrom('pet') .select('name') .whereRef('pet.owner_id', '=', 'person.id') .as('p'), (join) => join.onTrue() ) .select(['first_name', 'p.name']) .orderBy('first_name')
~~~

**Comment by igalklebanov** [comment]
Hey 👋 

Thank you! 💪 

Wanna submit a PR for these?

**Comment by KostyaTretyak** [comment]
[My project](https://github.com/ditsmod/realworld) is currently migrating to kysely. Maybe I'll find more bugs. If no one fixes the bugs described in this issue by the end of this migration, I will try to fix it.

**Comment by KostyaTretyak** [comment]
Incorrect example with plugins: https://koskimas.github.io/kysely/interfaces/KyselyPlugin.html#transformQuery

Need fix, like this:

```ts
const plugin: KyselyPlugin & { data: WeakMap<any, any> } = {
  data: new WeakMap<QueryId, SomeData>(),

  transformQuery(args: PluginTransformQueryArgs) {
    this.data.set(args.queryId, something);
    return args.node;
  },

  async transformResult(args: PluginTransformResultArgs) {
    const data = this.data.get(args.queryId);
    return args.result;
  },
};
```

By the way, I think `KyselyPlugin` need extend the to allow for other properties besides `transformQuery` and `transformResult`.
