### ISSUE TITLE
0.9.4 broke browser compatibility

### ISSUE THREAD

**Issue by steida** [koskimas/kysely#29]
I am running Kysely in the browser and everything seems to work except the version 0.9.4 broke browser compatibility with this line:

 ```ts
const startTime = process.hrtime.bigint();
```

There is no `process` in browsers of course. There are two possible workarounds.

1) Browser monkey-patching
2) Replace `process.hrtime` with universal code.

Both can be done with https://github.com/kumavis/browser-process-hrtime.

The solution depends on your Kysely vision. If it's aimed to be Node.js only, then it's up to users to monkey patch the environment. But I suppose Kysely can be easily universal, e.g. used in React Native as well.

**Comment by koskimas** [comment]
I guess we could use `performance.now()`? Would that work for you?

Since browser compatibility is not a goal and Kysely has no tests for it, things like this will probably continue to happen, but I can try to avoid node-only features from now on.

**Comment by steida** [comment]
Because I bet on Kysely for my project, I can help you with browser/nativeButNotNodeJS version. Should I send a PR?
