### ISSUE TITLE
db.fn.count() not see aliase of a table

### ISSUE THREAD

**Issue by KostyaTretyak** [koskimas/kysely#295]
This code not works (but should):

```ts
import { Kysely } from 'kysely';

interface Table1 {
  property1: any;
}

interface Database {
  table_1: Table1;
}

declare const db: Kysely<Database>;

async function some() {
  await db.selectFrom('table_1 as t1')
    .select(db.fn.count('t1.property1').as('foundRows'))
    .executeTakeFirst();
}
```

`db.fn.count()` not see aliase `t1`.

**Comment by igalklebanov** [comment]
Hey 👋 

In order for `.count` to be aware of current query's context, you must use it in the following way:

```ts
  await db.selectFrom('table_1 as t1')
    .select(eb => eb.fn.count('t1.property1').as('foundRows'))
    .executeTakeFirst();
```

**Comment by KostyaTretyak** [comment]
Oh, yes. Yesterday I worked for a long time on the migration to Kysely and did not see my mistake. It seems obvious now =).

**Comment by Nithur-M** [comment]
hey @igalklebanov, this query returns count value less than the actual value, do you know why?

**Comment by igalklebanov** [comment]
> hey @igalklebanov, this query returns count value less than the actual value, do you know why?

Hey 👋 

`count(column)` counts all rows, nulls excluded.
`count(*)` counts all rows, nulls included.

This could be the reason you're getting an unexpected number.

**Comment by Nithur-M** [comment]
Thanks for the response. When I run the query in MySQL workspace, it returns the expected results. Also, how to construct the second query in kysely?

**Comment by igalklebanov** [comment]
> Thanks for the response. When I run the query in MySQL workspace, it returns the expected results. Also, how to construct the second query in kysely?
> 
> [edit]: just checked my table and there is no null value for the column I am querying.

That's odd. Do you mind opening a new issue?
