### ISSUE TITLE
Index-Accessed Types from other Tables

### ISSUE THREAD

**Issue by nikeee** [koskimas/kysely#300]
Hi!

I'm just playing around with kysely. It looks really nice!

I was trying to make `PetTable.owner_id` refer to the `id` column of the `PersonTable`, so it ensures to be the same type and is more refactoring-safe. Tried this using an indexed access type:

```ts
interface PersonTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>
}

interface PetTable {
  id: Generated<number>
  owner_id: PersonTable["id"]
}
```

To my understanding, this would make `owner_id` be a `Generated<number>`. If I got `Generated<number>` correctly, kysely now thinks that `owner_id` will be supplied by the database. It seems that this is not what I want. Is there something to get `owner_id: number`, so it is the same base type of `PersonTable.id`?

In the special case for `Generated<T>`, this could be achieved using a simple `infer`:
```ts
type ColumnReference<Table, Column extends keyof Table> =
    Table[Column] extends Generated<infer BaseType>
        ? BaseType
        : Table[Column];

interface PetTable {
  id: Generated<number>
  owner_id: ColumnReference<PersonTable, "id">
}
```
However, kysely may contain more type wrappers that I'm not aware of.

Would this even be considered good practice in the kysely context?

**Comment by igalklebanov** [comment]
Hey 👋

Chances a string column will change over time are pretty slim.

Regardless, try to keep it simple with the types.

```ts
type PersonId = string

interface Person {
  id: Generated<PersonId>
}

interface Pet {
  person_id: PersonId
}
```

**Comment by nikeee** [comment]
Well, havent thought of using a plain type alias. This should suffice. Thank you!
