### ISSUE TITLE
Creating a Partial Index

### ISSUE THREAD

**Issue by nikeee** [koskimas/kysely#302]
Sorry for creating that many issues/questions.

While doing #301, I tried to create a partial index. Namely, I tried to achieve this:
```sql
CREATE INDEX post_expiration
ON post (expiration)
WHERE expiration IS NOT NULL
```

[SQLite](https://sqlite.org/partialindex.html) and [Postgres](https://www.postgresql.org/docs/current/indexes-partial.html) support partial indices. I'm not quite sure about the situation with MySQL/MariaDB.

I could not find a builder method for this, but I managed to [abuse `expression` for this](https://wirekang.github.io/kysely-playground/?p=f&i=-NMaBRrRK8T7IOeb7ICF):

```ts
db.schema.createIndex("post_created_at")
    .on("post")
    .expression(sql`expiration DESC) WHERE (expiration IS NOT NULL`)
```

Which results in this SQL:
```sql
CREATE INDEX `post_created_at` ON `post` (expiration DESC)
WHERE
  (expiration IS NOT NULL)
```

Well, that's obviously not the way to use `createIndex`. Is the last resort falling back to raw SQL here? Would this be something worth considering for a solution on a query builder level?

**Comment by koskimas** [comment]
We could add `where` methods to the index builder.
