### ISSUE TITLE
No autocomplete in VS Code with GitHub Copilot enabled

### ISSUE THREAD

**Issue by Farnsi** [koskimas/kysely#307]
Little off topic, but i think it is too specific to ask it at stackoverflow / reddit, i think it is more a problem of VS Code and or Copilot, but i hope somebody has a suggestion:

As soon as you write something like `db.selectFrom('user').where('` you got the description box and a list with possible fields.

With Copilot enabled, you got only the description box without a field list.

Is there something we can do to show the field list when copilot is enabled?

**Comment by koskimas** [comment]
At the code level, no. Sounds like a configuration issue or a bug in vscode/copilot.
