### ISSUE TITLE
More aggregate functions such as `array_agg` and `json_agg`

### ISSUE THREAD

**Issue by rliang** [koskimas/kysely#31]
It seems like this library currently only supports a subset of aggregate functions like `count`, `max` and `min`. Would it be possible to support `array_agg` or `json_agg`?

**Comment by koskimas** [comment]
Sure, we can add shortcuts for more aggregate functions. However, you can use `db.raw` to call any aggregate or other function. You can even create your own type-safe helpers easily.

```ts
await db
  .selectFrom('person')
  .innerJoin('pet', 'pet.owner_id', 'person.id')
  .select(db.raw<Pet[]>('json_agg(pet)').as('pets'))
```

**Comment by rliang** [comment]
I see. It's good that it's possible to use `db.raw` as a workaround. But it would be nicer if we didn't have to manually specify `<Pet[]>`, which is relatively error-prone.

It is possible to write a type-safe wrapper for these array aggregate functions, such that the array type is automatically inferred?

**Comment by koskimas** [comment]
I don't know. Maybe.

**Comment by rliang** [comment]
Thanks for the help. My use case is mostly within subqueries. After fiddling around, I came up with the following generic wrapper, which seems to produce both correct SQL and Typescript types:

```ts
function json_agg<DB, TB extends keyof DB, O = {}>(qb: QueryBuilder<DB, TB, O>) {
  return db.raw<O[]>(`(select jsonb_agg(x) from (??) x)`, [qb]);
}

await db
    .selectFrom("person")
    .select([
      "id",
      (qb) =>
        json_agg(
          qb
            .subQuery("pet")
            .whereRef("pet.owner_id", "=", "person.id")
            .select("pet.name")
        ).as("pets"),
    ])
    .executeTakeFirst() // type is { id: string, pets: { name: string }[] }
```

**Comment by t-indie** [comment]
unfortunately, when I try db.raw I get ` Property 'raw' does not exist on type 'Kysely<Database>'.ts`(2339)


example:

```ts
export async function getAll(
    db: Kysely<Database>,
    id: bigint
): Promise<any[] | undefined> {
    db.raw;
    const result = await db
        .selectFrom(tableName)
        .where('id', '=', id)
        .selectAll(tableName)
        .execute();
    return result;
}
```

**Comment by koskimas** [comment]
`db.raw` was replaced by the `sql` template tag [a while ago](https://github.com/koskimas/kysely/releases/tag/0.17.0).

Now you'd do something like this:

```ts
function jsonb_agg<DB, TB extends keyof DB, O = {}>(
  qb: SelectQueryBuilder<DB, TB, O>
) {
  return sql<O[]>`coalesce((select jsonb_agg(x) from (${qb}) x), '[]'::jsonb)`
}

const result = await ctx.db
  .selectFrom('person')
  .select([
    'person.id',
    (qb) => jsonb_agg(qb.selectFrom('pet').selectAll().whereRef('pet.owner_id', '=', 'person.id')).as('pets'),
  ])
  .execute()
```

**Comment by nbabaka** [comment]
Hello! I tried to use jsonb_agg function, but return value is always string.

`  (qb) => jsonb_agg(qb.selectFrom('artifact').select('url').whereRef('artifact.build_id', '=', 'build.id')).as('artifact')`

but kysely returns

`artifact: '[{"url": "xxx"}, {"url": "xxx" }]'`

How to cast the return value from string to object array?

Thank you
