### ISSUE TITLE
Type narrowing with `where` clauses

### ISSUE THREAD

**Issue by sds** [koskimas/kysely#310]
I tried searching through the issues / PRs list but wasn't able to find anything that seemed relevant to this topic, but please feel free to redirect if a discussion already exists.

We want the ability to have the nullability of a column narrowed automatically if a sufficient `where` clause is provided. For example:

```ts
interface Person {
  first_name: string;
  last_name: string | null;
}

await db
  .selectFrom('person')
  .selectAll()
  .where('last_name', 'is not', null)
  .execute(); // Would love to have this typed as { first_name: string; last_name: string }
```

We looked into implementing our own `whereNotNull` helper using the guidance in [Extending using module augmentation](https://github.com/koskimas/kysely/blob/master/recipes/extending-kysely.md#extending-using-module-augmentation), but realized that we might need some [additional types exported](https://github.com/koskimas/kysely/blob/8f1678b07af98ccffab40a9986d80a70b07d25e1/src/parser/select-parser.ts#L67-L168) to do the necessarily narrowing.

With that said, we understand that extensions written in this way **are explicitly not supported**, so wanted to check with you to see if there were any plans / ideas around supporting type narrowing via `where` clauses. This definitely couldn't be made to work in all cases, but if you are only using `StringReference`s to table columns it seems like it should be inferable from the schema.

**Comment by koskimas** [comment]
This has been answered before many times. The short answer is that narrowing would only be possible in trivial cases and it isn't worth the added complexity for the types.

**Comment by koskimas** [comment]
See #335

**Comment by igalklebanov** [comment]
#380 will help deal with the pain. 🩹
