### ISSUE TITLE
[Question] Why does each function on the query builder create a new instance of the class?

### ISSUE THREAD

**Issue by BlakeB415** [koskimas/kysely#311]
I have been reading through the codebase and I am curious as to why each method on the query builder creates a new instance of the class. This could probably also be done by passing the same instance on, so I'm just wondering if this was a conscious decision due to some use-case or whether it just happened to be implemented that way. 

Also, what is the resource impact of this sort of thing? Creating a new instance each time a method is chained doesn't sound that efficient.

**Comment by koskimas** [comment]
You can't change the type of a variable in typescript, but method calls like `select` need to change the type of the query builder. Mutable API is not possible.

Immutable API also works better with functional programming, which is more and more popular these days.

The impact on performance is negligible. You can create new instances hundreds of millions of times per second.
