### ISSUE TITLE
Postgres SearchPath

### ISSUE THREAD

**Issue by pratikpparikh** [koskimas/kysely#313]
How do i apply searchpath to my postgres connection?

https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PATH

Regards,
Pratik Parikh

**Comment by igalklebanov** [comment]
Hey 👋 

Kysely supports explictly stating schema names. 
It also provides [`.withSchema(schema)`](https://koskimas.github.io/kysely/classes/Kysely.html#withSchema) as a shortcut to prepend given schema name to all references.

For further details refer to https://github.com/koskimas/kysely/blob/master/recipes/schemas.md.

Not being explicit about schemas can be a footgun as far as type-safety goes.
Imagine having 2 tables with the same name but a different structure in different schemas.

You can extend the built-in postgres dialect, override `PostgresDriver.acquireConnection` as follows:

```ts
async acquireConnection(): Promise<DatabaseConnection> {
  const connection = await super.acquireConnection()

  await connection.executeQuery(CompiledQuery.raw(`set search_path to ${schemas.join(',')}`)) // you can pass a schemas value from your dialect's configuration, or have it hard-coded.

  return connection
}
```

@koskimas is this something worth adding to the core as optional prop @ `PostgresDialect`?

**Comment by koskimas** [comment]
I don't think this should be an option since it requires extra query on each connection. We already have `onCreateConnection`. Although I haven't given the `onCreateConnection` hook much thought lately. We should probably make running queries on the connection cleaner. Or at least document it better.
