### ISSUE TITLE
InsertResult insertID type uses bigInt instead of number

### ISSUE THREAD

**Issue by harisraharjo** [koskimas/kysely#317]
Why the types uses `bigInt | undefined` instead of `number | bigInt | undefined` ? isn't it too restricting because bigInt type is never going to happen early on?

**Comment by koskimas** [comment]
Kysely wraps the integer in a bigint.

**Comment by harisraharjo** [comment]
@koskimas Sorry for pinging you, but isn't it better if we only wrap it with `BigInt` if the count is greater than 2^53 which is the official threshold recommendation from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#usage_recommendations) ? this could also improve performance I think

**Comment by koskimas** [comment]
It would be a bad API if the value changed based on the size of the value. Performance-wise this is insignificant. Inserting a row takes some milliseconds and even if you remove all waiting time, tens or hundreds of microseconds of CPU time. Converting a number to a Bigint takes nanoseconds. So the insert itself takes tens or hundreds of thousands of times longer. At best you could speed things up by 0.001% to 0.01% by making the API more difficult to use. Not a good tradeoff.

**Comment by harisraharjo** [comment]
Ah okay thanks for the explanation!

**Comment by suchcodemuchwow** [comment]
@koskimas Sorry for reviving this issue but I have found while looking for bigint issue I am having before creating a new issue. 

`kysely-codegen` generates `number` type for auto increment id's in `planetscale`. I can manually go and edit all the typings but it doesn't really feel like a correct approach. Do you think it's an issue on codegen or it works as expected?

**Comment by suchcodemuchwow** [comment]
@koskimas Ohh I am sorry I think that's not a project you are involved but a 3rd party 😅

**Comment by koskimas** [comment]
This issue is about the `InsertResult` type that's returned if you don't return anything from an insert query using `returning`. The `InsertResult` is not related to the table/column types you provide to Kysely. It's always the same.
