### ISSUE TITLE
how to auto serialize/deserialize json type data in sqlite?

### ISSUE THREAD

**Issue by subframe7536** [koskimas/kysely#318]
thanks for your excellent work!

currently i use 
```ts
function json<T>(obj: T): RawBuilder<T> {
  return sql`${JSON.stringify(obj)}`
}
```
to serialize,
but how to deserialize? plugin or manually `JSON.parse()`?

**Comment by igalklebanov** [comment]
Hey 👋 


You can write a plugin that transforms the result. Try parsing strings, catch and return as-is.

We're not confident something like that can be added to core and handle all edge cases.
