### ISSUE TITLE
Feature Request: where allow raw builder

### ISSUE THREAD

**Issue by AzSiAz** [koskimas/kysely#32]
Hello again 👋 

Seem like you can't use `.where` with `.raw` method, to use `BETWEEN` for exemple

**Comment by koskimas** [comment]
Yep, that's probably a good idea. I'll add versions of `where`, `orWhere`, `having`, `orHaving`, `on` and `orOn` that take a single `RawBuilder` instance.

Still, I'd use `where('foo', '>', a).where('foo', '<', b)` instead of a raw `between` statement.
