### ISSUE TITLE
Support postgres extensions, particularly ltree?

### ISSUE THREAD

**Issue by trompx** [koskimas/kysely#321]
Hey,
I didn't find info about it anywhere else so asking it here.
I've been waiting for a long time for [prisma to support ltree extension](https://github.com/prisma/prisma/issues/2568) but to no avail.
Does kysely supports postgres extensions, and particularly the ltree extension?

**Comment by koskimas** [comment]
What kind of support are you after? Since kysely is just a query builder, you can build any query. The operators needed by `ltree` stuff should mostly already exist, and if some don't you can use

```ts
where('foo', sql`<the missing operator>`, "*.Foo.Bar.*")
```

**Comment by trompx** [comment]
Thanks and sorry for the confusion, I thought prisma/kysely were kind of similar so assumed it needed, as prisma, some sort of specific implementations to support postgres extensions.
I'll close and eventually reopen if I have issues in the future.
