### ISSUE TITLE
Add defaultValues method for insert query

### ISSUE THREAD

**Issue by johncsnyder** [koskimas/kysely#323]
Hey 👋  I've just started playing around with kysely, and so far it's a very cool project 🚀  

I've run into the case where a table has all columns with default values (I'm using postgres), in which case you could do:
```
INSERT INTO table DEFAULT VALUES returning id;
```

I couldn't find a built-in method to do this... instead I was able to build this statement using:
```
const result = await db
    .insertInto('table')
    .expression(() => sql`default values`)
    .returning('id')
    .executeTakeFirstOrThrow();
```

Maybe we could add a `defaultValues()` method so we could do:
```
const result = await db
    .insertInto('table')
    .defaultValues()
    .returning('id')
    .executeTakeFirstOrThrow();
```

WDYT?

**Comment by igalklebanov** [comment]
Hey 👋 



I'm on the fence on this one..

Pros:
- Relevant to both PostgreSQL & SQLite.
- "Safer" if Kysely does it.
- Good first issue.

Cons:
- Seems like a very rare use case.
- There's an easy workaround.

  PG / SQLite (as suggested above):
  ```ts
  db.insertInto('table').expression(sql`default values`) // insert into "table" default values
  ```

  MySQL:
  ```ts
  db.insertInto('table').columns([]).values({}) // insert into `user` () values ()
  ```

- It doesn't improve QoL in a significant way.

**Comment by johncsnyder** [comment]
I'd be happy to contribute if you'd like to add it.

A compromise could be to add some documentation to covers this use case?

For example, adding an example to https://koskimas.github.io/kysely/classes/InsertQueryBuilder.html#expression that demonstrates `expression` called with an `sql` tag.

**Comment by koskimas** [comment]
I don't think this deserves a method. Such a rare use case.

> For example, adding an example to

Sure we can add an example there, but for future reference: you can use the `sql` tag __anywhere__.
