### ISSUE TITLE
[help] how to get table column type in plugin?

### ISSUE THREAD

**Issue by subframe7536** [koskimas/kysely#328]
reference to #318, I want to get the type of each table column in plugin while querying select to judge whether it needs to deserialize, but `SelectQueryNode` doesn't provide🧐

my code here
```ts
export class SerializeParametersPlugin implements KyselyPlugin {
  readonly #serializeParametersTransformer: SerializeParametersTransformer
  readonly #deserializer: Deserializer
  #data: WeakMap<QueryId, SelectQueryNode>

  constructor(opt: SerializeParametersPluginOptions = {}) {
    this.#serializeParametersTransformer = new SerializeParametersTransformer(
      opt.serializer,
    )
    this.#deserializer = opt.deserializer || defaultDeserializer
    this.#data = new WeakMap()
  }

  transformQuery(args: PluginTransformQueryArgs): RootOperationNode {
    const { node, queryId } = args
    if (node.kind === 'SelectQueryNode') {
      this.#data.set(queryId, node)
    }
    return this.#serializeParametersTransformer.transformNode(args.node)
  }

  // deserialize in select
  parseResult(ctx: SelectQueryNode, rows: any[]): any[] {
    const { from, selections } = ctx
    const { froms } = from
    for (let i = 0; i < froms.length; i++) {
      const element = froms[i] as SchemableIdentifierNode
      // const { identifier } = element
      // console.log(element)
    }
    // console.log(froms, selections ? selections[0] : '')
    // return []
  }

  async transformResult(
    args: PluginTransformResultArgs,
  ): Promise<QueryResult<UnknownRow>> {
    const { result, queryId } = args
    const { rows } = result
    const ctx = this.#data.get(queryId)
    if (rows && ctx && ctx.kind === 'SelectQueryNode') {
      return {
        ...args.result,
        rows: this.parseResult(ctx, rows),
      }
    }
    return args.result
  }
}

```

**Comment by igalklebanov** [comment]
Hey 👋 

Runtime type information will never be included in the syntax tree.

You can configure custom result column casting at the driver level. E.g. `pg` has [pg-types](https://www.npmjs.com/package/pg-types) module for that.

**Comment by subframe7536** [comment]
All right. I found a [lib](https://www.npmjs.com/package/zodsql) and will try it later.

**Comment by subframe7536** [comment]
In addition, maybe I need the graph of plugin lifecycle.

for instance, I'm confused about the execution sequence and trigger events about `transformColumn`, `transformColumnUpdate`, `transformColumnDefinition` and `transformUpdateQuery`

**Comment by igalklebanov** [comment]
`zod` will do the trick. I'm not sure you need a lib to use it with kysely.

The issue is that it'll only cover your schema. Queries often introduce result columns not in schema. 

Sure, you could write `zod` result schemas for such queries, but it becomes a burden to maintain.

**Comment by koskimas** [comment]
> for instance, I'm confused about the execution sequence and trigger events about transformColumn, transformColumnUpdate, transformColumnDefinition and transformUpdateQuery

Those are not plugin hooks. The transformer is not strictly related to plugins, but you can use it in a plugin. A transformer is simply a helper class for transforming a query node tree into another tree. A transformer walks the query node tree depth first and transforms each node. So every child node gets transformed before their parent node does.

**Comment by koskimas** [comment]
@igalklebanov Already answered the original question. Getting the column type would mean executing separate metadata queries and Kysely will never do that. It would cause unpredictable performance issues and would be very surprising thing for a query builder to do.
