### ISSUE TITLE
Postgres: is prepared statement feature currently used?

### ISSUE THREAD

**Issue by ilijaNL** [koskimas/kysely#329]
Hello, inspecting the implementation of postgres dialect and driver at https://github.com/koskimas/kysely/blob/fdc7b36c4823898ede69fe11959cb5bd695eeb94/src/dialect/postgres/postgres-driver.ts#L103 I do not see that the queryId is used (should be 2nd argument looking at the  usage references). Does this mean that the prepared statement feature is not used (https://node-postgres.com/features/queries#prepared-statements)?

**Comment by koskimas** [comment]
NO.

**Comment by ilijaNL** [comment]
You are right, but sometimes it can be an useful optimization especially when the pool is small and query is complex. 

I guess current workaround is to .compile() and calling the pg.query directly.
