### ISSUE TITLE
Add support for "ref" to also reference previously used parameters.

### ISSUE THREAD

**Issue by nicksrandall** [koskimas/kysely#331]
I'm using the same variable (parameter) multiple times in the same query and it would be nice if I could reference it instead of creating multiple params of the same value.

**Comment by igalklebanov** [comment]
Hey 👋 

You mean something like:

```sql
select ($1 * "height") as "height", ($1 * "width") as "width"
from "boxes"
where ($1 * "height") < $2 and ($1 * "width") < $3

[0.25, 15, 20] 
```

?

**Comment by koskimas** [comment]
@nicksrandall Could you provide some further info ⬆️

**Comment by QuentinJanuel** [comment]
Hey, I've faced this limitation as well while migrating from `pgtyped` to `kysely`, so I can provide one use case:
I had a query with 2 list parameters:
```sql
select * from table where val1 in $$list and val2 in $$list
```
and `list` could get very large.
With `pgtyped`, referencing $$list at 2 different places didn't increase the amount of pg parameters. But with Kysely it doubled, reaching the 65535 limit.

Here, I could refactor it to
```sql
select * from table where val1 = any($$list) and val2 = any($$list)
```
to avoid having this much parameters at all but I'm not sure if the execution plans are identical, and even if they were in this scenario I think this could still be useful. 😕
