### ISSUE TITLE
Type mismatch between InsertId and ID field retrieved by Kysley's select

### ISSUE THREAD

**Issue by TaxTool** [koskimas/kysely#332]
**Problem**

There is a type mismatch between insertId and the object's id when I retrieve it from select. 

**Expectation**
I'm expecting that Kysely will make both fields bigint. 

**Supporting info**
An example table in MySQL that is causing a mismatch when I retrieve vs insert. 
```
 const createUsersTable = await sql`CREATE TABLE users (
    user_id bigint NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (user_id)
  ).execute(db);
```
How I'm retrieving the user
``` 
      db.selectFrom("users")
      .selectAll()
      .where("user_id", "=", userId)
      .executeTakeFirst();
```

` expect(retrievedUser?.user_id).toEqual(insertId);`
I get the following error.
`  AssertionError: expected '5' to deeply equal 5n`

**Comment by TaxTool** [comment]
The issue was being caused by using `kysely-planetscale`. 

I had to create a custom cast function so that numbers would be returned as bigints.

**Comment by igalklebanov** [comment]
Seems like an issue should be opened at `kysely-planetscale`.
