### ISSUE TITLE
MySQL SSL Connection?

### ISSUE THREAD

**Issue by AshleyJackson** [koskimas/kysely#333]
Hello,

I am attempting to use PlanetScale with Kysely and it is failing to connection due to an SSL issue.

Does Kysely support (Or have plans to support) SSL for MySQL?
I've found a previous ticket about supporting SSL for PostgreSQL, but nothing about MySQL.

Thanks.

**Comment by koskimas** [comment]
You pass the mysql2 driver pool instance to the dialect. You can configure it using any options it supports. If it doesn't support it, then neither can kysely.

**Comment by koskimas** [comment]
If you are using [this](https://github.com/depot/kysely-planetscale) then you need to ask the question in their GitHub. We have no control over third party dialects.
