### ISSUE TITLE
Filtering by is not null does not ensure the type is not null

### ISSUE THREAD

**Issue by dqii** [koskimas/kysely#335]
```
 const query = ctx.db
           .selectFrom('person')
           .selectAll()
           .where('last_name', 'is not', null)
```
In the returned type, last_name is not typed as string, but is typed as string | null

**Comment by koskimas** [comment]
This would only work in trivial cases but would seriously complicate the types. Not worth it.

**Comment by dqii** [comment]
Thank you for the response! That makes sense.

**Comment by igalklebanov** [comment]
#380 will help deal with the pain. 🩹
