### ISSUE TITLE
camelCase is not handling tables with single character

### ISSUE THREAD

**Issue by dqii** [koskimas/kysely#336]
`person_x_friend` seems to map to `personXFriend` with the camelcase plugin (as expected) but when calling

`await kysely.updateTable('personXFriend')`

The generated query uses `person_xfriend`

**Comment by koskimas** [comment]
There's an `underscoreBetweenUppercaseLetters` setting for this case

```ts
new CamelCasePlugin({ underscoreBetweenUppercaseLetters: true })
```

**Comment by dqii** [comment]
Thank you!
