### ISSUE TITLE
Insert return incompatible with type

### ISSUE THREAD

**Issue by TrueCarry** [koskimas/kysely#337]
I have function
```ts
export interface Key {
  id: Generated<number>
  name: string
}
export async function saveKey(): Promise<Key> {
  const res = await db
    .insertInto('keys')
    .values({
      name: walletName,
    })
    .returningAll()
    .execute()
  return res[0]
}
```

But i'm getting error:
![image](https://user-images.githubusercontent.com/5431520/220876768-4174c84b-5162-488b-820e-06eb7a68ab22.png)

Maybe there's a way to use Generated<number> as valid number in types?

**Comment by igalklebanov** [comment]
Hey 👋 

You should use `Promise<Selectable<Key>>` as return type.

Also, you can simplify your function by:

```ts
  return await db
    .insertInto('keys')
    .values({
      name: walletName,
    })
    .returningAll()
    .executeTakeFirstOrThrow()
```
