### ISSUE TITLE
Allow subQuery in `.values()`

### ISSUE THREAD

**Issue by rliang** [koskimas/kysely#34]
Currently, it doesn't seem possible to do something like
```ts
db.with("A", db => {
  db.selectFrom("B").selectAll().where("id", "=", 1)
}).insertInto("C").values({
  foo: qb => qb.subQuery("A").select("id")
});
```
It should be possible to work around this using `raw`, but it's not type-safe. But perhaps the `InsertValueExpression` type could be modified to also accept subqueries?

**Comment by koskimas** [comment]
Thanks for bringing this up! I hadn't considered the `with` queries. You can already do this:

```ts
db.with("A", db => {
  db.selectFrom("B").selectAll().where("id", "=", 1)
}).insertInto("C").values({
  foo: db.selectFrom('X').select('id')
});
```

but you can't refer to the common table expressions defined using `with`. I'll add the callback version ASAP.

**Comment by koskimas** [comment]
In case you didn't notice [0.11.4 version](https://github.com/koskimas/kysely/releases) now fixes this.
