### ISSUE TITLE
[question] insert generated ID into junction table after insert?

### ISSUE THREAD

**Issue by nvsd** [koskimas/kysely#341]
Currently, I'm doing something like:

```TS
const [{id}] = db.insertInto('mainTable').values({name: 'some name'}).returning('id').execute();
await db.insertInto('junctionTable').values({mainTableId: id}).execute();
```
Is there something obvious that I'm missing that would allow you to take the generated ID of a created item and then use that in a subsequent statement?

I'm just learning more SQL, so I'm likely missing something.

**Comment by nvsd** [comment]
Ah knew there had to be something. Thanks for the answer and for including the term so I could read up on it.

**Comment by koskimas** [comment]
@nvsd I had an error in the example. It's now updated.

**Comment by nvsd** [comment]
Ah, cool thanks for following up!
