### ISSUE TITLE
Log compiled query in error

### ISSUE THREAD

**Issue by ElliotAtAcuityMD** [koskimas/kysely#342]
Per this comment, I would like to suggest an improvement to the logging flow:

https://github.com/koskimas/kysely/issues/24#issuecomment-994893505

It would be useful to expose the compiled query on the error log too. This can help when debugging timeouts. I'm happy to open a pr implementing this if it seems reasonable. Thanks for the great library!

**Comment by koskimas** [comment]
See the comment above the one you linked https://github.com/koskimas/kysely/issues/24#issuecomment-991641298

**Comment by ElliotAtAcuityMD** [comment]
Thanks for the response. I do see that there is a custom log function but it does not expose the compiled query at the *error* level. Am I misunderstanding?

In the `runtime-driver` kysely logs the error, but does not pass the `compiledQuery` reference. I would like to pass `compiledQuery` because it can be useful to debug many errors.

**Comment by koskimas** [comment]
Oh, crap. Sorry about that. Yeah, we could definitely pass in the query too.
