### ISSUE TITLE
Where expression "RangeError: Too many parameter values were provided"

### ISSUE THREAD

**Issue by jtlapp** [koskimas/kysely#345]
What am I not understanding about expressions? The following:

```ts
    users = await db
      .selectFrom("users")
      .selectAll()
      .where(sql`handle != '${handle}'`)
      .execute();
```

Gives me this error in `better-sqlite3`:

> RangeError: Too many parameter values were provided

A search for this error in the `better-sqlite3` repo yielded [a scenario](https://github.com/WiseLibs/better-sqlite3/issues/486) where the query included both named and anonymous parameters.

(I realize Kysely provides another way to do this; I'm just trying to understand expression arguments.)

I'm lovin' this library, BTW.

**Comment by koskimas** [comment]
I don't know exactly what's causing the error but I think your query has an extra set of apostrophes.

This query:

```ts
    users = await db
      .selectFrom("users")
      .selectAll()
      .where(sql`handle != ${handle}`)
      .execute();
```

should result in this SQL:

```sql
select * from "users" where handle = ?
```

your query would lead to

```sql
select * from "users" where handle = '?'
```

and and "extra" parameter that's not used in the query since `'?'` is a string literal.

**Comment by jtlapp** [comment]
That fixed it. And now it's in issues for the next person who makes this mistake. Thank you!
