### ISSUE TITLE
Temporary Tables

### ISSUE THREAD

**Issue by Fyko** [koskimas/kysely#35]
Hello! I was curious how you'd advise implementing temporary tables with this package, or if there's support for it.

**Comment by koskimas** [comment]
Currently there's no support for temporary tables, but you can of course create one using `db.raw`. Adding support to the table builder `db.schema.createTable` is easy and I can do that, but the other problem is the lifetime of the session.

Temporary tables are automatically dropped at the end of the session, but Kysely uses a connection pool internally. Using a pool means that the connection is not ended after you are done with it, and therefore the session is not either. A later query might get a connection (session) that already has a temporary table created.

On postgres (at least) you can specify `on commit drop` which means that temporary tables are dropped at the end of the running transaction. This means you could do something like this with the current API:

```ts
const result = await db.transaction().execute((trx) => {
  await trx.schema
    createTable('some_temp_table')
    .temporary() // Doesn't exists yet
    .addColumn('foo', 'text')
    .addColumn('bar', 'integer')
    .onCommit('drop') // Doesn't exists yet
    .execute()

  // The `some_temp_table' would exist for the rest of the transaction
  // and would get dropped at the end of it.
})
```

Another thing is that you'd need to add the temporary tables to your `Database` interface. We could add a helper for that too if needed. Something like

```ts
trx = trx.withTableInterface<'some_temp_table', { foo: string, bar: number }>()
```

Which database are you using and how would you ideally like to use the temp tables?

**Comment by elderapo** [comment]
API suggestion:

```ts
const result = await db.transaction().execute(async tx => {
  interface Movie {
    id: string;
    stars: number;
  }

  interface Something {
    id: number;
    value: number;
  }

  interface TmpSchema {
    movie: Movie;
    something: Something;
  }

  const tmpDb = await tx
    .extendTemporarySchema<TmpSchema>()

    .createTable("movie")
    .addColumn("id", "text")
    .addColumn("stars", "integer")

    .createTable("something")
    .addColumn("id", "integer")
    .addColumn("value", "integer")

    .execute();

  const eliteMovie = await tmpDb.selectFrom("movie").where("movie.stars", "=", 1337).executeTakeFirst();
});
```

to make it as similar as possible to the normal schema definition. In this case `tmpDb` would have `Database & TmpSchema` type so queries on normal & temporarily tables can be safely type-checked :eyes: .

Bonus: before `.execute()` can be called the temporary schema builder could ensure all the tables/their columns are created/called (+/- [like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRlYBjGAhArsAGwBMBTKOAXzgDMoIQ4ByAI32LIFowBDGGMgHaMAUMLhxgA-lGrcMJOAFkIAN2AKEY8RKIAuOAGc0kgOYBuLeKPcoB-QNwhmZC+Iqjxk6bPkp6JGAALU0RLHXtHZyhXbRVuAlwSCKcXLXctLzIfBQAVcGQMQJIQblDtOBBVdX1lNRIYq38g031kJuCBczTRDAgBI0NC4tKAXhRjLDxCUigAHjywAqKSgD4ACgBKOAB6bbgAdQhcYjgBEhIiOBgICu4wK+5mAgVehJABODiEkgMrm5gAJ5gH5wIpQBRrIzoTpwEYrOAAIn4AA8YAitgEMAA6HFhLGVOprJDAPSI7jkhEAGkMMBsdjgAEYAMxMgDslA2eIM7VMRPCjIATEzqV9EvoGRKGRy8axppszEA)).

**Comment by koskimas** [comment]
I don't think we should add `createTable` or other schema methods to the transaction or `Kysely` class. There's a separate module for them in `db.schema`. What you suggest is a whole new abstraction on top of `SQL` and that's not the goal of Kysely. There's no `extendTemporarySchema` concept in SQL.

**Comment by koskimas** [comment]
The next version (0.12.0) will support the creation of temporary tables with or without the `on commit` statement.
