### ISSUE TITLE
Graphql Types Issue

### ISSUE THREAD

**Issue by quinnvaughn** [koskimas/kysely#351]
I'm having an issue with GraphQL expecting a normal string from an id, whereas it's actually returning `Generated<string>`. Any way to fix this or am I basically screwed with the integration?

**Comment by koskimas** [comment]
You probably found the answer already, but you shouldn't use the table interfaces as row types directly. There are helpers like `Selectable<YourTableType>`, `Updateable<YourTableType>` and `Insertable<YourTableType>`.

In most cases you shouldn't even use explicit types and instead trust the type inference.

**Comment by quinnvaughn** [comment]
Hey so

**Comment by quinnvaughn** [comment]
Yeah, so I am using pothos and I had to pass in the normal usertable to my db instance, and the selectable version to everything else, otherwise I was getting massive type issues.
