### ISSUE TITLE
Are parameters sanitized by Kysely?

### ISSUE THREAD

**Issue by blackhaj** [koskimas/kysely#354]
I am loving Kysely - huge thanks for the incredible library.

**Question:**
Would the parameter (rawInputFromUser) passed into the following query be sanitized and safe from SQL injection?

```ts
const result = db
      .selectFrom('Table')
      .selectAll()
      .where('Column', '=', rawInputFromUser)
      .execute()
```

**Comment by koskimas** [comment]
Take a wild guess 😉

**Comment by blackhaj** [comment]
Of course I thought the answer would be "yes" 😅 . But I couldn't find any mention of it in the docs so I wanted to check as it was key for a piece of work I was doing.

Thanks for responding
