### ISSUE TITLE
Reuse timestamp columns

### ISSUE THREAD

**Issue by leonvisscher** [koskimas/kysely#356]
I want created_at & updated_at columns on each table in my postgres database. Currently, I am adding
```
.addColumn('created_at', 'timestamptz', (col) =>
  col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull(),
)
.addColumn('updated_at', 'timestamptz', (col) =>
  col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull(),
)
```

to each table definition in my migration. Is there a way to reuse the columns or another method of not having to copy/paste these columns for each table definition?

**Comment by igalklebanov** [comment]
Hey 👋 

The best option imho is to simply create a helper, something like:

```ts
function withTimestamps(qb: CreateTableBuilder): CreateTableBuilder {
  return qb.addColumn('created_at', 'timestamptz', (col) =>
      col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull(),
    )
    .addColumn('updated_at', 'timestamptz', (col) =>
      col.defaultTo(sql`CURRENT_TIMESTAMP`).notNull(),
    )
}

await withTimestamps(kysely.schema.createTable('myTable')).execute()
```

Other risky option involves using [module augmentation](https://github.com/koskimas/kysely/blob/master/recipes/extending-kysely.md#extending-using-module-augmentation).

**Comment by koskimas** [comment]
@igalklebanov Should we add the `call` function to all builders making this possible:

```ts
await kysely.schema.createTable('myTable').call(withTimestamps).execute()
```

?

**Comment by noppa** [comment]
A method to make chaining helpers easier would be awesome! Just wondering if `call` is the best name for it, given that it's a bit overloaded with `Function.prototype.call`. Maybe `pipe` like RxJS has, or `thru` [like in Lodash](https://lodash.com/docs/4.17.15#thru), or even just `chain` or `to`?

**Comment by koskimas** [comment]
I like `chain`

**Comment by koskimas** [comment]
I like `chain`. It's a better name than `call` but changing the method name would be a breaking change and we shouldn't rename it without consideration.

**Comment by leonvisscher** [comment]
This is great, thanks all!

**Comment by koskimas** [comment]
Actually, `CreateTableBuilder` already has the `$call` method.
