### ISSUE TITLE
Is there a reason why my tables dont have the names I want?

### ISSUE THREAD

**Issue by StillWorking** [koskimas/kysely#363]
As mentioned before, I have a migratior file and a migration I wrote thats being implemented

runMigrations:
```
import { Migrator, FileMigrationProvider } from 'kysely'
import { promises as fs } from 'fs'
import * as path from 'path'
import { db } from './db'

const migrator = new Migrator({
    db,
    provider: new FileMigrationProvider({
        fs,
        path,
        migrationFolder: 'backend/database/migrations'
    }),
})

migrator.migrateToLatest()
```
and the migration in question:
```
import { Kysely } from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
  // Create MuscleGroup table
  await db.schema
    .createTable('muscle_group')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('name', 'varchar')
    .execute();

  // Create Exercise table
  await db.schema
    .createTable('exercise')
    .addColumn('id', 'serial', (col) => col.primaryKey())
    .addColumn('name', 'varchar')
    .addColumn('muscle_group_id', 'integer', (col) =>
      col.references('muscle_group.id')
    )
    .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable('exercise').execute()
  await db.schema.dropTable('muscle_group').execute()
}
```

after node runs the migration file I'm getting this:
![image](https://user-images.githubusercontent.com/50076057/225984072-e35bad0c-ec44-4d0e-8994-e04c74125f1c.png)

Not sure why the table names are like that. Help would be appreciated.

**Comment by koskimas** [comment]
Those tables are internal kysely bookkeeping tables. Your migrations have not been run for whatever reason.

**Comment by StillWorking** [comment]
As an aside, I double checked, my user has all access to create tables, I used Prisma to create the migration and it created the tables. Except I don't want to use Prisma, Would appreciate feedback

**Comment by koskimas** [comment]
Well you're not giving me much to work with. I'd guess the folder you're pointing to doesn't exist. The path is relative while node world with absolute paths. You are not printing any errors in your migration script so you are missing all of them. Maybe copy the script from the readme, or just use Prisma 😉

**Comment by StillWorking** [comment]
Good callout
```failed to migrate
Error: Cannot find module 'backend/database/migrations/CreateTables.ts'
```

**Comment by StillWorking** [comment]
Dont know why it cant find it because it definetly exists
![image](https://user-images.githubusercontent.com/50076057/226057531-9d9da420-f746-4195-949d-c6e8f5247564.png)

**Comment by koskimas** [comment]
You need to use absolute paths. And if you're running the compiled JavaScript code, make sure the absolute path points to the compiled migrations and NOT the typescript migrations.

**Comment by StillWorking** [comment]
Thank you that worked! Perhaps this should be added to the docs just in case noobs like me ask the same question
