### ISSUE TITLE
Improving the where's comparsion syntax.

### ISSUE THREAD

**Issue by spa5k** [koskimas/kysely#37]
```ts
const person = await db
    .selectFrom('person')
    .innerJoin('pet', 'pet.owner_id', 'person.id')
    .select(['first_name', 'pet.name as pet_name'])
    .where('person.id', '=', 1)
    .executeTakeFirst()
```

In this query, the where function where user needs to manually enter the '=' or other similar comparison operators in the middle, imo it does not look that good and many more improvements can be made to it.

So taking inspiration from Prisma, which tbf has a great query builder and the api that they have implemented.

It can be changed to something like this - 

```ts
  const person = await db
    .selectFrom('person')
    .innerJoin('pet', 'pet.owner_id', 'person.id')
    .select(['first_name', 'pet.name as pet_name'])
    .where('person.id': {
    	gt: 1
    })
    .executeTakeFirst()
    ```
  You can look for more examples here - https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#get-all-post-records-where-likes-is-greater-than-9

**Comment by spa5k** [comment]
this can result in better and easier intellisense support,

**Comment by koskimas** [comment]
We'd need to come up with a name for every single operator. There are tens of them. Also how about raw operators. Also the plan is to keep the code looking as much like SQL as possible.

I do agree that it's odd that the join methods don't have a comparator, while `where`, `having` etc. do. We could add an operator parameter to the `join` methods too, but that's a bit odd as the operator will be `=` 99% of the time.
