### ISSUE TITLE
Use UNNEST in query

### ISSUE THREAD

**Issue by Jeromearsene** [koskimas/kysely#370]
I have one PostgreSQL query with this condition:

```sql
WHERE EXISTS (
    SELECT
    FROM UNNEST(persons."name") elem
    WHERE elem LIKE '%toto%'
)
```

But I can't do this with Kysely:

```typescript
.whereExists((qb) =>
        qb
        .selectFrom(({ ref }) => sql<string>`UNNEST(${ref('persons.name')})`.as('elem'))
        .selectAll()
        .where('elem', 'like', '%toto%')
)
```

Have you an idea of problem ?

Thanks

**Comment by igalklebanov** [comment]
Hey 👋 

> But I can't do this with Kysely

I'm missing some context and a way playground link.

**Comment by koskimas** [comment]
Okay, it seems that the column gets the same name as the table in that case. Assuming you are actually unnesting an array, this should work:

```ts
qb.selectFrom(({ ref }) => sql<{ elem: string }>`UNNEST(${ref('persons.name')})`.as('elem'))
  .selectAll()
  .where('elem', 'like', '%toto%')
```

You should probably wrap that into an `unnest` helper function to make the query cleaner.

**Comment by koskimas** [comment]
And actually I don't think you need the outer expression builder in your original example

```ts
.whereExists((eb) =>
  eb.selectFrom(unnest(eb.ref('persons.array'), 'elem'))
    .selectAll()
    .where('elem', 'like', '%toto%')
)
```

**Comment by Jeromearsene** [comment]
> Hey 👋
> 
> > But I can't do this with Kysely
> 
> I'm missing some context and a playground link.

Thanks for you reactivity !

I edit my initial message with precisions.

[The link to Playground](https://wirekang.github.io/kysely-playground/?p=h&i=eyJreXNlbHlWZXJzaW9uIjoiMC4yMy4zIiwiZGlhbGVjdCI6InBvc3RncmVzIiwidHMiOiJpbnRlcmZhY2UgREIge1xuICB1c2VyOiBVc2VyVGFibGVcbn1cblxuaW50ZXJmYWNlIFVzZXJUYWJsZSB7XG4gIGlkOiBHZW5lcmF0ZWQ8c3RyaW5nPlxuICBuYW1lOiBzdHJpbmdbXVxuICBjcmVhdGVkX2F0OiBHZW5lcmF0ZWQ8RGF0ZT5cbn1cblxucmVzdWx0ID0ga3lzZWx5XG4gIC5zZWxlY3RGcm9tKCd1c2VyJylcbiAgLnNlbGVjdChbJ2lkJywgJ25hbWUnXSlcbiAgLndoZXJlRXhpc3RzKChxYikgPT5cbiAgICBxYlxuICAgICAgLnNlbGVjdEZyb20oKHsgcmVmIH0pID0%2BXG4gICAgICAgIHNxbDxzdHJpbmc%2BYFVOTkVTVCgke3JlZigndXNlci5uYW1lJyl9KWAuYXMoJ2VsZW0nKSxcbiAgICAgIClcbiAgICAgIC5zZWxlY3RBbGwoKVxuICAgICAgLndoZXJlKCdlbGVtJywgJ2xpa2UnLCAnJXRvdG8lJyksXG4gIClcbiJ9).

Kysely version: `0.23.5`
