### ISSUE TITLE
How to select with functions?

### ISSUE THREAD

**Issue by TomMettam** [koskimas/kysely#374]
I'm trying to figure out how to accomplish something like

`SELECT UNIX_TIMESTAMP(slotWeeks.startDate) as slotWeekStart`

I tried using an sql template but it seems not to be accepted by .select()

What's the way to accomplish this in Kysely?

**Comment by koskimas** [comment]
You need to provide an alias for the selection using the `as` method.

```ts
.select([
  'foo',
  'bar',
  sql<string>`UNIX_TIMESTAMP(slotWeeks.startDate)`.as('slotWeekStart')
])
```
