### ISSUE TITLE
Full stops in table names breaks Kysely?

### ISSUE THREAD

**Issue by AshleyJackson** [koskimas/kysely#382]
Hello, 

I have attempted to run the below code and it errors out.
I've tested this on another test databse on mine and it has the same error.

```
export async function getByEmail(email: string) {
    const result = await db
        .selectFrom("test-lms.online.users")
        .where("email", "=", email)
        .selectAll()
        .execute();
    return result;
}
```

This prevents me from successfully running against a table that has full stops in the name.
Is this expected behaviour?

**Comment by koskimas** [comment]
Unfortunately this is the expected behaviour. Full stops are interpreted as schema/table separators. There's no reasonable way to support this use case either.

**Comment by domdomegg** [comment]
Will note the same applies to column names with full stops / periods in them

**Comment by igalklebanov** [comment]
Hey 👋

You could implement a plugin similar to `CamelCasePlugin` that translates from/to dot notation.
