### ISSUE TITLE
AWS Lambda Node 14 Support? 

### ISSUE THREAD

**Issue by samsouder** [koskimas/kysely#39]
@koskimas I was wondering (due to our heavy use of AWS services, including Lambda) why this package is heavily tied to Nodejs version 16?

Sadly, even though 16.x is the LTS, AWS is behind and doesn't support anything past 14.x without jumping through hoops which means we can't stay updated with the new features being added to Kysely.

**Comment by koskimas** [comment]
> why this package is heavily tied to Nodejs version 16

Heavily? There's one single `replaceAll` method call that doesn't work on node 14. I can remove that and support 14 for now.  In general, I don't like to support ancient node or typescript versions. The next version will support node 14.

**Comment by samsouder** [comment]
Forgive me, maybe 'strongly tied' would have been better wording. I meant only the Node 16 requirement being enforced in the package.json file which was keeping our Lambda-deployed code from using this code.

I completely understand the reluctance to support something beyond the LTS version. I was speaking to whether you felt there were too many 16.x-specific calls in the package to warrant consideration of older versions for a time.

Thanks for looking into this and your work on this package in general!

**Comment by koskimas** [comment]
0.12.2 now supports node 14.
