### ISSUE TITLE
How to filter is not null?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#4]
I have tried the following 

`.where('jtdPhoneLogCustomer.id', 'is not', 'null')`
`.where('jtdPhoneLogCustomer.id', 'is not', null)`

But none of them work. 

```
...
.where('user.id', 'is not', 'null')

```

compiled to
```
// sql
select from
...
where "user"."id" is not $1

// binding
[ 'null' ]
```
Looks like the problem is kysely pass null as parameter

Maybe we should add another chain method `whereNull` and `whereNotNull` similar to knex

```
.whereNotNull('user.id')
```

**Comment by koskimas** [comment]
Use null, not 'null'

**Comment by koskimas** [comment]
Use null, not 'null'

**Comment by koskimas** [comment]
I don't want to ad another method. We would need to add `whereNull`, `whereNotNull`, `orWhereNull`, `orWhereNotNull`, `havingNull`, `havingNotNull`, `orHavingNull`, `orNotHavingNull`, `onNull`, `onNotNull`, `orOnNull` and `orOnNotNull`. I rather fix the bug.

Good catch!
