### ISSUE TITLE
camelcase plugin does not work when column name include `_${number}`.

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#40]
### Example

``` ts

selectFrom('company').select(['amountSpend_12m']).limit(1).compile()

// log: select "amount_spend_12m" from "company" limit $1


selectFrom('company').select(['amountSpend_12m']).limit(1).execute()

// log: [ { amountSpend12m: 0 } ]

expected // log: [ { amountSpend_12m: 0 } ]

```

**Comment by koskimas** [comment]
It's not possible to make that work.

**Comment by xiaoyu-tamu** [comment]
this is a bug, idk why this issue got closed.

**Comment by xiaoyu-tamu** [comment]
```sql
create table company
(
    id               integer generated by default as identity
        constraint company_pk
            primary key,
    amount_spend_12m int
); 
```

you can try this ddl with camelcase plugin

**Comment by koskimas** [comment]
The camel case plugin simple runs all identifiers (column names, table names etc.) through a `toSnakeCase` function and then the returned column names through a `toCamelCase` function. When kysely receives a column named `amount_spend_12m` from the db, how could it possibly know that it's supposed to transfer it to a mixture of cameCase and snake case `amountSpend_12m`?

We don't actually know which `select`s map to which returned columns. Figuring that out would be super difficult.

**Comment by xiaoyu-tamu** [comment]
if the column name is `amount_spend_12m`, how should user define it in typescript interface?

**Comment by koskimas** [comment]
`amountSpend12m`

**Comment by xiaoyu-tamu** [comment]
it doesn't work. kysely transform it to amount_spend12m

**Comment by koskimas** [comment]
See the documentation https://koskimas.github.io/kysely/interfaces/CamelCasePluginOptions.html#underscoreBeforeDigits

**Comment by koskimas** [comment]
And you're welcome for the free help once again!
