### ISSUE TITLE
Using withSchema and transaction on QueryCreator

### ISSUE THREAD

**Issue by capaj** [koskimas/kysely#410]
I am currently using prisma, but I am looking into using kysely instead for queries which prisma cannot do or does slowly.

I have a problem with schemas though.
I have tried to use https://github.com/kysely-org/kysely/blob/master/site/docs/recipes/schemas.md#2 but how do I run a DB transaction with it?
It only returns QueryCreator<DB> which does not have `transaction` on it.
Am I missing something? Is `transaction` deliberetely omitted?

**Comment by capaj** [comment]
ok, I was able to work around it with 

```ts
    return await kyselyDb.transaction().execute(async (trx) => {
      // @ts-expect-error
      trx = trx.withSchema(dbSchema) // workaround for now until kysely supports schemas better
      // ... rest of the code
    })
```

but I hate it

**Comment by igalklebanov** [comment]
Hey 👋 

Another option, not documented in the recipe, is to use `WithSchemaPlugin`:

```ts
import { Kysely, WithSchemaPlugin } from 'kysely'

const kyselyDb = new Kysely<Database>({
  // ...
  plugins: [
    new WithSchemaPlugin(dbSchema),
  ],
})

kyselyDb.transaction().execute(async (trx) => {
  // ...
})
```

While cleaner than the workaround you mentioned, it doesn't fit all use cases.

**Comment by igalklebanov** [comment]
`.withSchema` allows on-the-fly application of the same plugin for a specific flow.
Using the plugin at Kysely instantiation means that the schema is always applied (unless you run `.withoutPlugins()`) when using that instance.

**Comment by capaj** [comment]
Thanks. 
I think the plugin way should be added to that recipe https://github.com/kysely-org/kysely/blob/master/site/docs/recipes/schemas.md#2
