### ISSUE TITLE
Using generics?

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#42]
I'm trying to use generics to be able to pass around an entity definition, and use kysely to operate on it. Is this possible?

With this code, calling selectAll().execute() is typed as an array - (Person & Pet)[]. Would expect it to be ItemSchema[K][]

```
type Pet = {  
    ownerName: string  
}  
type Person = {  
    name: string  
}  
type ItemSchema = {
    persons: Person
    pets: Pet
}
type EntityDef<K extends keyof ItemSchema> = {
    table: TableExpression<ItemSchema, K>
}
function doStuff<K extends keyof ItemSchema>(db: Kysely<ItemSchema>, def: EntityDef<K>) {
    const results = db.selectFrom(def.table).selectAll().execute();
}
```

**Comment by koskimas** [comment]
`ItemSchema[keyof ItemSchema]` is `Person $ Pet`. Everything works correctly there. My have misunderstood how typescript works. The type cannot be narrower until you use the `doStuff` somewhere, but the implementation types cannot change based on the call site.
