### ISSUE TITLE
Improve addColumn for SQLite

### ISSUE THREAD

**Issue by steida** [koskimas/kysely#44]
SQLite [flexible typing](https://www.sqlite.org/flextypegood.html) requires special treatment.

A 'blob' data type and the ability to not specify type at all.

`A column with affinity BLOB does not prefer one storage class over another and no attempt is made to coerce data from one storage class into another. 
`

`If the declared type for a column contains the string "BLOB" or if no type is specified then the column has affinity BLOB.
`

Maybe adding 'blob' type to types is enough.

**Comment by koskimas** [comment]
I added the `blob` data type. sqlite should map that automatically to BLOB storage class.
