### ISSUE TITLE
Doing bulk queries with .raw() or something similar

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#46]
Right now I'm doing a couple of bulk queries (user input) using the sqlite client directly.

I'd like to incorporate this into kysely so i can hide my connection object entirely, and take advantage of kysely for locking/transactions. However I have 2 issues:

- Kysely only executes the first query I pass in using .raw().execute(). Standard behavior for sqlite with the methods the driver calls on the sqlite object.
- Even if this did work (I could modify the driver) the return types would not match. Sqlite kicks back an object that looks something like this for bulk queries (using exec()):

`{ columns: string[], values: any[][] }[]`

This obviously has 2 issues. 1 is that it may contain more than one result set, whereas kysely only expects one. The other is that if I run a query and need to know the column names, this will work, whereas kysely's standard type is an array of objects, so I won't know the column names if the query has no results.

Is this something you'd consider incorporating? Maybe a separate bulk() method, similar to the raw method but with a different response type. As far as I can tell it could be done, but would require modifying all of the drivers to either change the response type to 
`{ columns: string[], values: any[][] }[]` and then have kysely convert it to `object[]` outside of the driver for regular queries, or adding a separate executeBulkQuery() method to each driver's DatabaseConnection. Not sure if it's worth it, but otherwise anyone who wants to do bulk queries has to move the connection/locking/transaction logic outside of the kysely driver.

I'm also not sure what format postgres and mysql give back by default so that may be an issue as well.

**Comment by igalklebanov** [comment]
Multiple query requests are a security vulnerability, and are quite often disabled in RDBMSs by default.

I can see the benefits of optimizing mutation flows by running multiple inserts/updates/deletes without a transaction (less RTTs).
I know `mysql2` does support this with a flag (turned off by default).

This issue is open since 12.2021 and only gained 3 upvotes, so I'm not quite sure how common/important this pattern is.

**Comment by midwesterntechnology** [comment]
> Multiple query requests are a security vulnerability, and are quite often disabled in RDBMSs by default.
> 
> I can see the benefits of optimizing mutation flows by running multiple inserts/updates/deletes without a transaction (less RTTs). I know `mysql2` does support this with a flag (turned off by default).
> 
> This issue is open since 12.2021 and only gained 3 upvotes, so I'm not quite sure how common/important this pattern is.

Multiple query requests is probably less common than issue #2 - any query where you don't know the column names in advance, but do need them in the result, even if no rows are returned. It's probably not that common, but I could see use cases for this (basically any select * query if you don't know the table structure in advance). My use case was that I was writing an open source phpmyadmin style tool to administer an sqlite database running on wasm. Kysely's functionality is very useful here even though I didn't know the DB structure, but of course I also was needing to accommodate custom queries.

For me it is not a huge issue because I need to use a custom driver anyway - but if anyone has a similar use say with node, the stock drivers wouldn't allow them to accommodate it. And even in my case, it would be cleaner to keep all of the locking functionality within the Kysely driver, instead of exposing my DB connection object and mutex just for a handful of queries, and relying on the caller to utilize the mutex.

**Comment by igalklebanov** [comment]
Issue 2 can be solved with introspection / using kysely-codegen, am I missing something?

**Comment by midwesterntechnology** [comment]
True, introspection could cover anything where you just want to SELECT * from table. That's what I was doing for the simple table browsing portion of it since I had to introspect anyway to get the list of tables.

Really, I can't think of another use case for this besides directly user inputted queries with arbitrary column selection. For those of course there's nothing to introspect.

**Comment by igalklebanov** [comment]
> Really, I can't think of another use case for this besides directly user inputted queries with arbitrary column selection.

We can never be fully type-safe in such cases, best to always validate user input and if kysely doesn't infer something reasonable, to use `.castTo<Partial<Person>>()` or something.

---

Seems like all issues mentioned are quite uncommon, so I'll close this for now.

**Comment by midwesterntechnology** [comment]
> We can never be fully type-safe in such cases, best to always validate user input and if kysely doesn't infer something reasonable, to use `.castTo<Partial<Person>>()` or something.
> 
> Seems like all issues mentioned are quite uncommon, so I'll close this for now.

No problem. Just to be clear though this isn't a typing issue at all, these are all dynamic queries with unknown types, Record<string, unknown> essentially. It's really more of an escape hatch that allows you to hit the DB directly and get a raw response (that includes column names even if there are no results), but re-use the connection/functionality of whatever Kysely driver you are using.
