### ISSUE TITLE
Migrator shouldn't sort migrations

### ISSUE THREAD

**Issue by bullno1** [koskimas/kysely#52]
Currently, the returned record will be sorted.
There are several problems:

* One would need a proper naming scheme (e.g: ISO8601 prefix) and a process to enforce it.
  It is doable but that's more work.
* This does not allow a custom `MigrationProvider` to provide its own ordering scheme (e.g: linked list).

In other tools such as [alembic](https://alembic.sqlalchemy.org/en/latest/), a migration has a reference to a previous migration.
This allows the tool to sort migrations independent of file names.
This also provides another benefit: in a project with multiple developers, a situation where "forks" appear in the migration history can be easily detected: The history would no longer be a linear chain.

My proposal:

1. For backward compatibility, the current behavior would still be supported.
2. Extend the return type of `MigrationProvider.getMigrations` to `Record<string, Migration> | Migration[]`, or, if a name is needed for internal state tracking: `Record<string, Migration> | NamedMigration[]` where `NamedMigration = Migration & { name: string }`.
3. When `Migrator` gets a `NamedMigration[]`, it wouldn't sort and immediately use the array as is.
4. Change the compatibility code path of `Migrator` to generate `NamedMigration[]` from `Record<string, Migration>`.
5. Make `FileMigrationProvider` do the same.
6. Eventually remove `Record<string, Migration>` in the next major version.

**Comment by koskimas** [comment]
You can just provide an index (properly zero padded) as the migration name to turn the map into a list.
