### ISSUE TITLE
Expose API for fetching which migrations have run

### ISSUE THREAD

**Issue by thdxr** [koskimas/kysely#58]
We're building a UI around running these migrations and need to know which migrations have already run without directly querying the migrations table

**Comment by koskimas** [comment]
What do you think about adding a `getState` method for the `Migrator` that returns an object like this

```ts
interface MigrationState {
  // All migrations sorted by name.
  readonly migrations: ReadonlyArray<NamedMigration>

  // Index of the last executed migration.
  readonly currentIndex: number
}

interface Migration {
  up(db: Kysely<any>): Promise<void>
  down?(db: Kysely<any>): Promise<void>
}

interface NamedMigration extends Migration {
  readonly name: string
}
```

?

**Comment by thdxr** [comment]
We'd probably like the timestamp but this works as a starting point

**Comment by koskimas** [comment]
Maybe it's more future-proof to add a `getMigrations` method for `Migrator` that returns a list of these:

```ts
{
  name: string
  migration: Migration
  executedAt?: Date
}
```

`executedAt` would be undefined for unexecuted migrations. Or should we add an `executed` boolean as well?
