### ISSUE TITLE
Schema support

### ISSUE THREAD

**Issue by eudgen-dev** [koskimas/kysely#64]
Does kysely support work with custom schemas?

We are using PostgreSQL with custom schemas inside. How we can use kysely for this purpose?

Thanks for help.

**Comment by eudgen-dev** [comment]
Thanks for fast response.

Can we also use .withSchema method for  each  tables (from, joined)?

In other way  we have to define some table with schema and some tables without it

For example we have the next DB structure: 
schema1.pet
schema2.person

So it looks like this:

```
interface Database {
    pet: PetTable,
    'schema2.person': PersonTable,
}

await db.withSchema('schema1')
    .selectFrom('pet')
    .selectAll()
    .innerJoin('schema2.person as person', 'person.id', 'pet.owner_id')
    .execute()
```

Thanks

**Comment by koskimas** [comment]
I'm not sure I undestood the question. The example you provided should create this SQL:

```sql
select * from "schema1"."pet"
inner join "schema2"."person" as "person" on "person"."id" = "schema1"."pet"."owner_id"
```

Please open an issue if something doesn't work the way you expect it to.
```
