### ISSUE TITLE
Feature request: database introspection for generating automatic types

### ISSUE THREAD

**Issue by cridasilva** [koskimas/kysely#65]
It would be very interesting to have a feature similar to Prisma to avoid having to write the database types manually (especially with legacy databases).

**Comment by koskimas** [comment]
See [this](https://koskimas.github.io/kysely/classes/Kysely.html#introspection) and [this](https://koskimas.github.io/kysely/interfaces/DatabaseIntrospector.html).

```ts
const meta = await db.introspection.getMetadata()
```

Currently only basic information is available. Let me know what's missing and maybe we can add it. Kysely will probably never include a type generator itself.
