### ISSUE TITLE
Feature request: add a migration CLI (similar to Knex.js)

### ISSUE THREAD

**Issue by tairosonloa** [koskimas/kysely#66]
I saw that Kysely already has a [Migrator](https://koskimas.github.io/kysely/classes/Migrator.html) class, but I saw nothing about a migration CLI, that could allow to easily migrate up/down/latest with a CLI command, similar to [Knex.js one](https://knexjs.org/#Migrations-CLI)

**Comment by koskimas** [comment]
Probably not. The reason is explained in the readme.

**Comment by acro5piano** [comment]
I've created a thin CLI command. It works like a library instead of executable CLI, but reduces lots of boilerplate code.

https://github.com/acro5piano/kysely-migration-cli

Hope it helps
