### ISSUE TITLE
Operators in orderBy

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#68]
Is there any way to do something like this without using raw? Every SQL dialect I've used has supported the SQL equivalent.

`query.orderBy("column", "=", "X")`

**Comment by koskimas** [comment]
What does that do? Put the ones that evaluate to true first in arbitrary order and the rest after, again in arbitrary order? I don't think that's really a common use case.

**Comment by midwesterntechnology** [comment]
Yes it sorts by the results of the expression. For example right now I'm trying to select from a table, but show a certain set of items first, before applying my regular ordering. Since I'm using offset and limit and it can be a very large table (100K+ rows), there's not really another good way to do it. Would look something like this:

query.orderBy(eb => eb.condition("id", "in", selectedItems), "desc").orderBy("otherColumn")

Not the most common, but not extremely rare either, I've seen similar logic on a few projects.

But really this is not just about orderBy but ExpressionBuilder, I think it would make sense to have the ability to cleanly do a condition off of an ExpressionBuilder, since every SQL engine I've ever used considers a condition an expression just the same as a function, subquery, column reference, etc, all of which ExpressionBuilder currently supports.

query.orderBy(eb => eb.condition("column", "=", "value"))
query.select(eb => eb.condition("column", "=", "value"))
query.distinctOn(eb => eb.condition("column", "=", "value"))
query.groupBy(eb => eb.condition("column", "=", "value"))
query.where("column", "=", eb => eb.condition("otherColumn", "=", "value"))

**Comment by koskimas** [comment]
It would only make sense to add something like that if it was more common than any other expression in the world. I don't think it is.

**Comment by koskimas** [comment]
What would this do

```ts
query.where("column", "=", eb => eb.condition("otherColumn", "=", "value"))
```

it would only make sense if that compiled into

```sql
column = (otherColumn = $1)
```

which would only make sense for boolean columns.

**Comment by midwesterntechnology** [comment]
>It would only make sense to add something like that if it was more common than any other expression in the world. I don't think it is.

Not quite sure what you mean by if it was more common than any other expression in the world?

Going back to ORDER BY specifically though, have you ever used ORDER BY CASE? Not an obscure thing, lots of use cases for that, and many of the simpler ones (where another column is not referenced with the THEN clause) are accomplished by ordering by an expression, or more likely multiple expressions. There is also SELECT CASE which works similarly - however simple boolean expressions do not typically fill the gap as well for those use cases.

https://stackoverflow.com/search?q=sql+order+by+case

Simple example:

```
ORDER BY CASE
WHEN status = "published" THEN 1
WHEN status = "private" THEN 2
WHEN status = "draft" THEN 3
```

Expression equivalent:

```
ORDER BY status = "published", status = "private", status = "draft"
```

>which would only make sense for boolean columns.

Yeah this one is an unlikely example for real world use. Was just trying to think of all the areas where ExpressionBuilder was used, thought one of them might jump out.
