### ISSUE TITLE
`defaultTo` adding quotations which fails functions

### ISSUE THREAD

**Issue by justindra** [koskimas/kysely#69]
When creating a table during migration and setting defaultValues using `defaultTo`, it automatically adds `'` (quotes) around the input. This causes things to fail when passing in a function.

The following:
```ts
await db.schema
    .createTable(tableName)
    .ifNotExists()
    .addColumn('id', 'uuid', (col) =>
      col.primaryKey().defaultTo('gen_random_uuid()')
    )
    .execute()
```

Produces
```
sql: `create table if not exists "users" ("id" uuid default 'gen_random_uuid()' primary key)
                                                            ^
```

Which causes the error:
```
ERROR BadRequestException: ERROR: invalid input syntax for type uuid: "gen_random_uuid()"; SQLState: 22P02
```

Ideally it should produce
```
sql: `create table if not exists "users" ("id" uuid default gen_random_uuid() primary key)
```

**Comment by koskimas** [comment]
The values passed to `defaultTo` are interpreted as values. You can use

```ts
col.primaryKey().defaultTo(sql`gen_random_uuid()`)
```

**Comment by koskimas** [comment]
This is all documented in the `defaultTo` method's documentation. It can be found in the [API documentation](https://koskimas.github.io/kysely/interfaces/ColumnDefinitionBuilderInterface.html#defaultTo) and [in the source code](https://github.com/koskimas/kysely/blob/319122bd8a50006bee6966036929ad5cbde475ec/src/schema/column-definition-builder.ts#L123)
