### ISSUE TITLE
Is it possible to make RHS of `where` expression typesafe?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#7]
Not sure this is a feature request or bug, currently, the RHS of where expression is not aware of type.

```ts

interface Person {
  id: number;
  first_name: string;
  last_name: string;
  gender: 'male' | 'female' | 'other';
}

const db = new Kysely<{ person: Person }>({});


// this will throw in runtime because WHATEVER is not a valid enum value.
// is it possible to throw in compile time?

db.selectFrom('person')
  .selectAll()
  .where('gender', '=', 'WHATEVER'); 

```

### related code

https://github.com/koskimas/kysely/blob/master/src/query-builder/query-builder.ts#L250-L254

I attempted to catch LHS type into a variable C, but without luck, since `'male' | 'female' | 'other' | string` will widen the type to string.

```ts
where<C extends ReferenceExpression<DB, TB>>(lhs: C, op: FilterOperatorArg, rhs: ValueExpressionOrList<DB, TB, C>): QueryBuilder<DB, TB, O>;

export type ValueExpression<DB, TB extends keyof DB, C> = DB[TB][C] | PrimitiveValue | AnyQueryBuilder | QueryBuilderFactory<DB, TB> | RawBuilder<any> | RawBuilderFactory<DB, TB>;

export type ValueExpressionOrList<DB, TB extends keyof DB, C> = ValueExpression<DB, TB, C> | ValueExpression<DB, TB, C>[];
```

—-

update

if we could get the exact type of LHS, do we still need `PrimitiveValue` type?

**Comment by koskimas** [comment]
I think we could drop the `PrimitiveValue` type and just use the exact type when known. If the LHS is a raw instance, we can't infer the type. In all other cases we should be able to.

I'll try to implement this.
