### ISSUE TITLE
alterTable().addForeignKeyConstraint() missing callback parameter

### ISSUE THREAD

**Issue by mendellerner** [koskimas/kysely#75]
Works:
```TypeScript
await db.schema
    .createTable('app')
    .addColumn
    .addForeignKeyConstraint(
      'fk',
      ['id'],
      'main',
      ['appid'],
      (cb) => cb.onDelete('restrict')
    )
    .execute();
```

Doesn't Compile:
```TypeScript
await db.schema
    .alterTable('app')
    .addForeignKeyConstraint(
      'fk',
      ['appid'],
      'main',
      ['appid'],
      (cb) => cb.onDelete('restrict') // 5th parameter doesn't exist
    )
    .execute();
```

**Comment by mendellerner** [comment]
My apologies. 

It seems to me that the `addForeignKeyConstraint()` method on `alterTable` doesn't have the 5th parameter for the callback function `(cb) => cb.onDelete('restrict')` while that fifth parameter does exist on `createTable`'s implementation of `addForeignKeyConstraint()`

**Comment by koskimas** [comment]
The method returns the builder:

```ts
await db.schema
    .alterTable('app')
    .addForeignKeyConstraint(
      'fk',
      ['appid'],
      'main',
      ['appid'],
    )
    .onDelete('restrict')
    .execute();
```

The difference is that you can add multiple constraints using a single `CREATE TABLE` query --> callback
but only one using the `ALTER TABLE` query --> returns the builder

**Comment by mendellerner** [comment]
Thanks for the explanation.

That wasn't obvious to me but makes sense from an OOP perspective.

**Comment by koskimas** [comment]
I added documentation for the methods.

**Comment by mendellerner** [comment]
Thanks!
