### ISSUE TITLE
Insert or update multiple rows

### ISSUE THREAD

**Issue by kujtimiihoxha** [koskimas/kysely#76]
Hey there, thanks for this great package 🙌 .

I was wondering how I would write a query similar to 

```sql
INSERT INTO users (listid,email,age,name) VALUES (3,'john@gmail.com',26,"John"),
(3,'bob@gmail.com',32,"Bob"),
(3,'matt@gmail.com',29,"Matt"),
(2,'john@gmail.com',25,"John"),
ON DUPLICATE KEY UPDATE listid=VALUES(listid), 
email=VALUES(email), 
age=VALUES(age), 
name=VALUES(name);
```

I can see that you expose `onDuplicateKeyUpdate` but I am not sure how to make it so that I use the `VALUES` instead of a static value?.

For context, I am trying to use this to load/sync data between 2 data sources.

**Comment by koskimas** [comment]
Currently this is the only way to get that done

```ts
db.insertInto('users')
  .values([ row1, row1, ... ])
  .onDuplicateKeyUpdate({
    listid: sql`VALUES(listid)`,
    email: sql`VALUES(email)`,
    age: sql`VALUES(age)`,
    name: sql`VALUES(name)`,
  })
```

We could add a type-safe option by adding the `values` function to the function helper. Then this would be possible:

```ts
db.insertInto('users')
  .values([ row1, row1, ... ])
  .onDuplicateKeyUpdate({
    listid: (eb) => eb.fn.values("listid"),
    email: (eb) => eb.fn.values("email"),
    age: (eb) => eb.fn.values("age"),
    name: (eb) => eb.fn.values("name"),
  })
```

but that's a bit repetive. I've thought about adding another way to get the expression builder for these "mutation objects" like this:

```ts
db.insertInto('users')
  .values([ row1, row1, ... ])
  .onDuplicateKeyUpdate((eb) => ({
    listid: eb.fn.values("listid"),
    email: eb.fn.values("email"),
    age:  eb.fn.values("age"),
    name:  eb.fn.values("name"),
  }))
```

That's already a bit better. And with some destructuring, you'd get this:

```ts
db.insertInto('users')
  .values([ row1, row1, ... ])
  .onDuplicateKeyUpdate(({ fn: { values }}) => ({
    listid: values("listid"),
    email: values("email"),
    age:  values("age"),
    name:  values("name"),
  }))
```

**Comment by kujtimiihoxha** [comment]
@koskimas thanks for the reply, I think the first option is good enough for now. I just needed to know `a` way 😂

**Comment by koskimas** [comment]
It's hard to know what kind of free service you expect. You are the first one that decided to "laugh" at me for being too helpful. Won't make that mistake again with you

**Comment by Trolley33** [comment]
> It's hard to know what kind of free service you expect. You are the first one who decided to "laugh" at me for being too helpful. Won't make that mistake again with you 🤷‍♂️

That'd be a really nice feature, especially if the strings in `values` are automatically escaped as `ref`s. I ran into the issue today that one of my columns is called `group` and took me a while to realize why I was getting a syntax error 😅.

**Comment by tombohub** [comment]
> Currently this is the only way to get that done
> 
> ```ts
> db.insertInto('users')
>   .values([ row1, row1, ... ])
>   .onDuplicateKeyUpdate({
>     listid: sql`VALUES(listid)`,
>     email: sql`VALUES(email)`,
>     age: sql`VALUES(age)`,
>     name: sql`VALUES(name)`,
>   })
> ```
> 
> We could add a type-safe option by adding the `values` function to the function helper. Then this would be possible:
> 
> ```ts
> db.insertInto('users')
>   .values([ row1, row1, ... ])
>   .onDuplicateKeyUpdate({
>     listid: (eb) => eb.fn.values('listid'),
>     email: (eb) => eb.fn.values('email'),
>     age: (eb) => eb.fn.values('age'),
>     name: (eb) => eb.fn.values('name'),
>   })
> ```
> 
> but that's a bit repetitive. I've thought about adding another way to get the expression builder for these "mutation objects" like this:
> 
> ```ts
> db.insertInto('users')
>   .values([ row1, row1, ... ])
>   .onDuplicateKeyUpdate((eb) => ({
>     listid: eb.fn.values('listid'),
>     email: eb.fn.values('email'),
>     age: eb.fn.values('age'),
>     name: eb.fn.values('name'),
>   }))
> ```
> 
> That's already a bit better. And with some destructuring, you'd get this:
> 
> ```ts
> db.insertInto('users')
>   .values([ row1, row1, ... ])
>   .onDuplicateKeyUpdate(({ fn: { values }}) => ({
>     listid: values('listid'),
>     email: values('email'),
>     age: values('age'),
>     name: values('name'),
>   }))
> ```

Hi!

Are you saying that first example is how it is possible right now, and all the other examples are not yet possible?

**Comment by koskimas** [comment]
You can also create a helper function like this:

```ts
function values<T>(ref: Expression<T>) {
  return sql`VALUES(${expr})`
}
```

and then use it like this

```ts
db.insertInto('users')
  .values([ row1, row1, ... ])
  .onDuplicateKeyUpdate(({ ref }) => ({
    listid: values(ref('listid')),
    email: values(ref('email')),
    age: values(ref('age')),
    name: values(ref('name')),
  }))
```

that's fully type-safe. You just need that extra `ref` call there.
