### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#8]
Hi koshimas.

I tried to migrated some personal scripts to kysely and noticed that SSL is not support yet.

I'm using postgres on Heroku, and they require connect over SSL.

It would be nice we could pass more options to `node-pg` https://node-postgres.com/features/ssl

**Comment by koskimas** [comment]
Thanks! Added in the latest version.

**Comment by koskimas** [comment]
https://github.com/koskimas/kysely/commit/90dd9e03328ccfe222caa79862c8d8f066747725
