### ISSUE TITLE
migrator class doesn't allow specifying a schema to put migration tables

### ISSUE THREAD

**Issue by DanielFGray** [koskimas/kysely#80]
It would be really nice if users could specify a schema to put the `kysely_migration` tables in (at least when using postgres I'm not sure how it would translate in other databases)

If this is already an existing feature I couldn't find it in the docs..

**Comment by koskimas** [comment]
So kysely should also create the schema right? Or can we expect it to exist?

**Comment by DanielFGray** [comment]
Great question. `create schema if not exists` would make sense to me, and I can't think of any reason why this wouldn't be desirable, except if you typo'd the schema name

**Comment by koskimas** [comment]
You can specify the schema like this

```ts
new Migrator({
  migrationTableSchema: 'some_schema'
})
```

in the next version.

**Comment by Marko351** [comment]
Is there any implementation available for MSSQL?

**Comment by koskimas** [comment]
@rafaelbsky that's what it's supposed to do. `migrationTableSchema` === "Schema for the migration tables". Not for your own tables.

You can bind your `Kysely` instance you give to `Migrator` to the schema using `db.withSchema('my_schema')` https://kysely-org.github.io/kysely-apidoc/classes/QueryCreator.html#withSchema
