### ISSUE TITLE
How do you drop table constraints without relying on sql?

### ISSUE THREAD

**Issue by sberlan-odeko** [koskimas/kysely#85]
When using `db.schema.createTable('foo')`, there are methods like `addCheckConstraint` / `addForeignKeyConstraint` / `addPrimaryKeyConstraint` / `addUniqueConstraint`, but `db.schema.alterTable('foo')` doesn't appear to have corresponding `drop*` methods on type `AlterTableBuilder`

Is it nested under another area? I see that a type `DropConstraintNode` but I imagine it's a parser type.

Going to use `sql` for now, so not up a creek or anything.

Version: 0.17.1

**Comment by koskimas** [comment]
I've forgot to implement the method in the query builder 😄 I'll add it soon.

Offtopic, but there's no parser. `DropConstraintNode` is something the query builder produces.

**Comment by sberlan-odeko** [comment]
Also noticed a signature difference between:

- `db.schema.createTable('foo').addColumn(columnName, dataType, columnBuilderCallback)`
- `db.schema.alterTable('foo').addColumn(columnName, dataType)`

I imagine same kind of situation? (also not a problem since I have the `sql` escape hatch)

**Comment by koskimas** [comment]
Nope, in that case the latter returns the builder. There's no need for the callback since you can only add one column in an alter table query. But that's been causing confusion to other people too, so maybe I need to make the API equivalent.

**Comment by koskimas** [comment]
```ts
db.schema
  .createTable('foo')
  .addColumn(columnName, dataType, b => b.notNull())
```

```ts
db.schema
  .alterTable('foo')
  .addColumn(columnName, dataType)
  .notNull()
```
