### ISSUE TITLE
Autocomplete only available on first select string

### ISSUE THREAD

**Issue by anthonyalayo** [koskimas/kysely#86]
Hi there,

First of all, thanks for this project! It's the closest to JOOQ that I've seen in TS, and that's a great thing.

I noticed when using `.select()`, autocomplete only seems to appear for the first string. All subsequent strings don't seem to have it.

Is this a known issue?

**Comment by anthonyalayo** [comment]
First column selected
![image](https://user-images.githubusercontent.com/17555572/165171256-4120d4a3-581d-4568-bcba-0be56710695c.png)

Subsequent column selected
![image](https://user-images.githubusercontent.com/17555572/165171300-74f2114c-00f9-49b0-998a-a30d9912315f.png)

**Comment by koskimas** [comment]
The select method only takes one string or an array. Multiple arguments are not supported.
