### ISSUE TITLE
Typing return values from select statements?

### ISSUE THREAD

**Issue by anthonyalayo** [koskimas/kysely#87]
Hey there,

Thanks for the project! I'm trying it out with TS, and I can't figure out how to type return values?

I attempted this:
```
    const a: Array<Words> = await db.selectFrom('words')
        .select(['words.id', 'words.word'])
        .execute();
```

Where words is this:
```
export interface Words {
  id: number;
  word: string;
  ...
  ...
}
```

but the compiler complains. Is there some docs/guide on typing the return value?

**Comment by koskimas** [comment]
You don't need to type the return values. You can trust the type inference.

But if for some reason you want to type the result, you need to use the correct type. In your example, you only select columns `id` and `word` and not all columns, so the correct type is `{ id: number, word: string }` and not `Words`.

```ts
    const a: Array<{ id: number, word: string }> = await db.selectFrom('words')
        .select(['words.id', 'words.word'])
        .execute();
```

or


```ts
    const a: Array<Pick<Words, 'id' | 'word'>> = await db.selectFrom('words')
        .select(['words.id', 'words.word'])
        .execute();
```

but it makes no sense to use explicit types with modern typescript. You an just leave it out:

```ts
    const a = await db.selectFrom('words')
        .select(['words.id', 'words.word'])
        .execute();
```

**Comment by anthonyalayo** [comment]
Thanks for the quick reply @koskimas! In terms of this comment:

> but it makes no sense to use explicit types with modern typescript. You an just leave it out:

I type the return values so that my IDE can autocomplete fields. Is there a better way to get that support?
