### ISSUE TITLE
Inner Join with more than 1 pair

### ISSUE THREAD

**Issue by anthonyalayo** [koskimas/kysely#88]
Hey there,

I'm attempting to InnerJoin with more than one key pair. I tried putting more than 3 arguments inside innerJoin(), but it seems to error out?

The documentation only shows an inner join with 2 fields:
```
  const person = await db
    .selectFrom('person')
    .innerJoin('pet', 'pet.owner_id', 'person.id')
    .select(['first_name', 'pet.name as pet_name'])
    .where('person.id', '=', id)
    .executeTakeFirst()
```

Thanks!

**Comment by koskimas** [comment]
Have you noticed that there's a quite extensive API documentation with lots and lots of examples? You can just ctrl-click the method to get to the documentation. Or visit here

https://koskimas.github.io/kysely/index.html

But here's a copy pasted example from the documentation:

```ts
await db.selectFrom('person')
  .innerJoin(
    'pet',
    (join) => join
      .onRef('pet.owner_id', '=', 'person.id')
      .on('pet.name', '=', 'Doggo')
  )
  .selectAll()
  .execute()
```

**Comment by anthonyalayo** [comment]
Ahh, I didn't catch that before, thanks! Let me check out this resource.
