### ISSUE TITLE
[Postgres] Column Array Type

### ISSUE THREAD

**Issue by mickiewicz** [koskimas/kysely#89]
Postgres supports arrays types. Is there a way to use arrays with postgres dialect?

**Comment by mickiewicz** [comment]
I've just found out that `DataTypeExpression` could be also `AnyRawBuilder`

`export declare type DataTypeExpression = ColumnDataType | AnyRawBuilder;`

so something like that worked:

```
await db.schema
    .createTable('test_table')
    .addColumn('custom_column_type', sql`uuid[]`)
    .execute();
```

**Comment by igalklebanov** [comment]
Hey 👋

https://kysely-org.github.io/kysely-apidoc/classes/CreateTableBuilder.html#addColumn
