### ISSUE TITLE
Join with Alias

### ISSUE THREAD

**Issue by ragokan** [koskimas/kysely#90]
Hey, how can I use *join* method in *select* with *alias*? 

When I execute this query:
```ts
  const posts = await db
    .selectFrom("post")
    .rightJoin("user", "user.id", "post.id")
    .selectAll()
    .execute();
 ```

I get this result:
```ts
  {
    id: 1,
    title: 'Hello world',
    userId: 1,
    username: 'myFirstUser',
    role: 'user'
  }
  ```
  
  But the result I actually would like to have is:
```ts
{
  id: 1,
  title: "Hello world",
  userId: 1,
  user: {
    id: 1,
    username: "myFirstUser",
    role: "user",
  },
}
 ```

  Or maybe: 
  ```ts
{
  post: {
    id: 1,
    title: "Hello world",
    userId: 1,
  },
  user: {
    id: 1,
    username: "myFirstUser",
    role: "user",
  },
}
  ```
  
  I don't know if it has something to do with *SQL* itself but I also sadly don't know how to use *SQL* deeply and I also searched for it's SQL query, sadly I did not find anything.

**Comment by koskimas** [comment]
Kysely is just a SQL query builder and doesn't provide anything like that. All it does is build SQL queries and provide a (hopefully) nice way to do that. Maybe some ORM would work better for your use case?

However, there are ways to get a structure like that using SQL, but it's not pretty. You can use aggregate functions like `jsonb_agg` on postgresql and `json_agg` on mysql, but the queries are complex and you need to know even more about how SQL works.

**Comment by ragokan** [comment]
> Kysely is just a SQL query builder and doesn't provide anything like that. All it does is build SQL queries and provide a (hopefully) nice way to do that. Maybe some ORM would work better for your use case?
> 
> However, there are ways to get a structure like that using SQL, but it's not pretty. You can use aggregate functions like `jsonb_agg` on postgresql and `json_agg` on mysql, but the queries are complex and you need to know even more about how SQL works.

I totally get it, let me do a search about SQL, thank you for your answer.
