### ISSUE TITLE
Unused Dialects Requiring Packages in Webpack Build

### ISSUE THREAD

**Issue by hheavener-kyd** [koskimas/kysely#92]
I am using the MySQL dialect with this library but whenever I bundle my app using webpack, the calls to [`import('pg')`](https://github.com/koskimas/kysely/blob/48c9934d3bebcd7a4d25b9e5b345425890ece998/src/dialect/postgres/postgres-driver.ts#L124) and [`import('better-sqlite3')`](https://github.com/koskimas/kysely/blob/48c9934d3bebcd7a4d25b9e5b345425890ece998/src/dialect/sqlite/sqlite-driver.ts#L99) prevent my project from building. 

I'm not sure why bundling the project triggers a call to these two imports. I only use the MySQL dialect class where the connection is established. If I comment out the `import` statements, my code builds and runs fine. However, I'm creating a build pipeline in our repository which will not have the commented-out code and I'm trying to figure out if:
 1. I need to fork this repo and maintain a version of it, or
 2. if there is a quick fix you can provide, or
 3. if you might know something I could do differently with webpack to resolve this issue

Let me know if I need to provide examples of my setup for you to review.

Thanks a ton!

P.S. this library is absolutely freaking gold. I LOVE it!

**Comment by koskimas** [comment]
I'm actually releasing a new version today that has absolutely no dependencies to anything whatsoever. All dependencies are passed from the outside, so this won't be a problem anymore.

For example, you'll create a `Kysely` instance like this:

```ts
import { createPool } from 'mysql2'

const kyselt = new Kysely<DB>({
  dialect: MysqlDialect({
    pool: createPool(mysqlConfig)
  })
})
```

**Comment by koskimas** [comment]
It's now released.
