### ISSUE TITLE
0.19.2: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by steida** [koskimas/kysely#95]
```
./node_modules/kysely/dist/esm/migration/file-migration-provider.js
Critical dependency: the request of a dependency is an expression
```

When used with Next.js. It's just a warning, compiled code works. It's probably this line: `const migration = await import(this.#props.path.join(this.#props.migrationFolder, fileName));`

I am not sure how to fix it. Do you have any idea?

**Comment by steida** [comment]
This is a workaround:

```ts
const migration = await import(/* webpackIgnore: true */this.#props.path.join(this.#props.migrationFolder, fileName));
```

I am not sure why Webpack parses it, because I don't use it. I hope there is no hidden reference 😅

**Comment by steida** [comment]
I put `console.log('test')` into `node_modules/kysely/dist/esm/migration/file-migration-provider.js` and it's called even after building despite I don't import it anywhere. That's weird.

**Comment by koskimas** [comment]
It's imported by the index file.

**Comment by steida** [comment]
@koskimas Of course, but that should be removed if not used.

**Comment by steida** [comment]
Btw, why `.ts` files are imported with `.js` extension?

<img width="1028" alt="Screenshot 2022-05-18 at 19 02 51" src="https://user-images.githubusercontent.com/66249/169100663-0eda0da9-53d6-4d47-8ba9-8d312b63ca11.png">

**Comment by koskimas** [comment]
Requirement of esm.

**Comment by steida** [comment]
@koskimas I will play with `dist/esm` folder to figure out why tree-shaking does not work. Then it should not warn I suppose.

**Comment by koskimas** [comment]
Does the webpackignore need to be inlined like that or can it be put above the line? Just thinking ahead when we need to add one of these for each bundler.

**Comment by steida** [comment]
@koskimas It must be inlined exactly like that.
