### ISSUE TITLE
Question: AWS Lambda and Connection Pooling (PostgresDialect)

### ISSUE THREAD

**Issue by SethThomas** [koskimas/kysely#96]
Thank you for the fantastic library!

I'm been experimenting with using kysely instead of [Node PG](https://node-postgres.com/) directly.  So far, I've found it to be an easy refactor.

I am using kysely in the context of AWS Lambda and RDS for Postgres (non-serverless option).  When using node-pg directly, I avoid using the connection Pooling mechanism and opt for using the PG Client directly.  This is due to the stateless execution environment of AWS Lambda and how Lambda _can_ "freeze" the execution environment between invocations. 

Having a look at the [PostgresDialogConfig](https://github.com/koskimas/kysely/blob/ba42803de18a274a8f569b80e159de231bd27ba5/src/dialect/postgres/postgres-dialect-config.ts#L6), I notice there is a required `pool` parameter.  I'm not sure this is what I want.

Is there a way for me to use kysely without a connection pool?  Alternatively, is there a recommended way to use kysely in AWS Lambda?

**Comment by koskimas** [comment]
This issue may also be of interest to you https://github.com/koskimas/kysely/issues/9

**Comment by SethThomas** [comment]
That works for me, thank you!

I'm actually using Kysely with Serverless Stack 🙂 

Unfortunately, I'm dealing with a legacy RDS Database that prevents me from using Aurora Serverless.  

Thanks again for the project, it's been fantastic to work with.

**Comment by smith558** [comment]
> That works for me, thank you!
> 
> I'm actually using Kysely with Serverless Stack 🙂
> 
> Unfortunately, I'm dealing with a legacy RDS Database that prevents me from using Aurora Serverless.
> 
> Thanks again for the project, it's been fantastic to work with.

How did you solve this? Did you end up staying with SST.dev? Considering using it in production as well for a db heavy application.
