### ISSUE TITLE
How to compare a UUID field

### ISSUE THREAD

**Issue by t-indie** [koskimas/kysely#97]
Firstly, thank you so much for maintaining this project and providing the insightful [example](https://github.com/koskimas/kysely/tree/master/example)

I have a PostgreSQL users table where the id is of type **UUID**, however when I use the where comparator I get this error "operator does not exist: uuid = character varying" 

```typescript
export async function findUserById(
    db: Kysely<Database>,
    id: string
): Promise<UserRow | undefined> {
    const user = await db
        .selectFrom(tableName)
        .where('id', '=', id)
        .selectAll(tableName)
        .executeTakeFirst();
    return user;
}
```

I found online that one should use this operator but unfortunately it throws an error
```typescript
.where('id::text', '=', id)
```

Any ideas would be appreciated.  Thanks in advance

**Comment by koskimas** [comment]
Either like this

```ts
.where(sql`id::text` '=', id)
```

or like this

```ts
function asUuid(val: string): RawBuilder<string> {
  return sql`${val}::uuid`
}
```

```ts
.where('id', '=', asUuid(id))
```

**Comment by T04435** [comment]
Should `kysely-codegen` generate UUIDs as string instead of number?

While none is correct(not uuid) that avoids the need for the above every time we query...
